.\" -*- coding: UTF-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH paste 1 "3 August 2014" "2014 年 7 月" "GNU coreutils 8.22"
.SH NAME
paste \- 合并文件的行
.SH SYNOPSIS
'nh
.fi
.ad l
\fBpaste\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[\fI选项\fR]… [\fI文件\fR]…
'in \n(.iu-\nxu
.ad b
'hy
.SH 描述
输出每个文件中顺序对应的行到标准输出，文件由 TAB 间隔。若无文件，或文件为 - 时，则读取标准输入。
.PP
针对长选项的强制参数对短选项来说也是强制的。
.TP 
\*(T<\fB\-d\fR\*(T>, \*(T<\fB\-\-delimiters\fR\*(T>=\fI列表\fR
由列表中的字符而非 TAB 来间隔文件
.TP 
\*(T<\fB\-s\fR\*(T>, \*(T<\fB\-\-serial\fR\*(T>
一次粘贴一个文件，而不是并发粘贴
.TP 
\*(T<\fB\-\-help\fR\*(T>
显示此帮助并退出
.TP 
\*(T<\fB\-\-version\fR\*(T>
输出版本信息并退出

GNU coreutils 在线帮助：<〈http://www.gnu.org/software/coreutils/>〉 汇报 paste 翻译故障 <〈http://translationproject.org/team/>〉
.SH 作者
由 David M. Ihnat 和 David MacKenzie 编纂。
.SH 版权
版权所有 © 2013 自由软件基金会。许可证 GPLv3+：GNU 通用公共许可证 第三版及后续版本 <〈http://gnu.org/licenses/gpl.html>〉。这是一个自由软件：您可以自由修订并分发它。在法律允许范围内不作任何保证。
.SH 继续阅读
\fBpaste\fR 的完整文档以一本 Texinfo 手册的形式维护。若您的计算机上妥善安装了 \fIinfo\fR 和 \fBpaste\fR 程序，这个命令
.PP
\fIinfo coreutils "paste invocation"\fR
.PP
应可让您调阅完整手册。
