'\" t -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH conky 1 2012-05-03 "" ""
.SH NAME
conky \- A system monitor for X originally based on the torsmo code, but more kickass. It just keeps on given'er. Yeah.
.SH SYNOPSIS
'nh
.fi
.ad l
\fBconky\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[
\fIoptions\fR
]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
Conky is a system monitor for X originally based on
torsmo. Since its inception, Conky has changed
significantly from its predecessor, while maintaining
simplicity and configurability. Conky can display just
about anything, either on your root desktop or in its own
window. Not only does Conky have many built-in objects, it
can also display just about any piece of information by
using scripts and other external programs.
.PP
Conky has more than 250 built in objects, including
support for a plethora of OS stats (uname, uptime, CPU
usage, mem usage, disk usage, "top" like process stats, and
network monitoring, just to name a few), built in IMAP and
POP3 support, built in support for many popular music
players (MPD, XMMS2, BMPx, Audacious), and much much more.
Conky can display this info either as text, or using simple
progress bars and graph widgets, with different fonts and
colours.
.PP
We are always looking for help, whether its reporting
bugs, writing patches, or writing docs. Please use the
facilities at SourceForge to make bug reports, feature
requests, and submit patches, or stop by #conky on
irc.freenode.net if you have questions or want to
contribute.
.PP
Thanks for your interest in Conky.
.SH COMPILING
For users compiling from source on a binary distro,
make sure you have the X development libraries installed
(Unless you provide configure with "--disable-x11"). This
should be a package along the lines of "libx11-dev" or
"xorg-x11-dev" for X11 libs, and similar "-dev" format for
the other libs required (depending on your configure
options). You should be able to see which extra packages
you need to install by reading errors that you get from
\&'./configure'. You can enable/disable stuff by giving
options to configure, but be careful with disabling. For
example: with --disable-math you won't get errors but
logarithmic graphs will be normal graphs and gauges
will miss their line. 
.PP
Conky has (for some time) been available in the
repositories of most popular distributions. Here are some
installation instructions for a few:
.PP
Gentoo users -- Conky is in Gentoo's Portage...
simply use "emerge app-admin/conky" for
installation.
.PP
Debian, etc. users -- Conky should be in your
repositories, and can be installed by doing "aptitude
install conky".
.PP
Example to compile and run Conky with all optional
components (note that some configure options may differ for
your system):
.TP 
\fB\*(T<\fBsh autogen.sh\fR\*(T> \fR\*(T<\fB# Only required if building from the git repo\fR\*(T> 
.TP 
\fB\*(T<\fB\&./configure\fR\*(T> \fR\*(T<\fB\-\-prefix=/usr \-\-mandir=/usr/share/man \-\-infodir=/usr/share/info \-\-datadir=/usr/share \-\-sysconfdir=/etc \-\-localstatedir=/var/lib \-\-disable\-own\-window \-\-enable\-audacious[=yes|no|legacy] \-\-enable\-bmpx \-\-disable\-hddtemp \-\-disable\-mpd \-\-enable\-xmms2 \-\-disable\-portmon \-\-disable\-network \-\-enable\-debug \-\-disable\-x11 \-\-disable\-double\-buffer \-\-disable\-xdamage \-\-disable\-xft\fR\*(T> 
.TP 
\fB\*(T<\fBmake\fR\*(T> \fR
.TP 
\fB\*(T<\fBmake install\fR\*(T> \fR\*(T<\fB# Optional\fR\*(T> 
.TP 
\fB\*(T<\fBsrc/conky\fR\*(T> \fR
.PP
Conky has been tested to be compatible with C99 C,
however it has not been tested with anything other than
gcc, and is not guaranteed to work with other
compilers.
.PP
.SH "YOU SHOULD KNOW"
Conky is generally very good on resources. That said,
the more you try to make Conky do, the more resources it is
going to consume.
.PP
An easy way to force Conky to reload your ~/.conkyrc:
"killall -SIGUSR1 conky". Saves you the trouble of having
to kill and then restart. You can now also do the same with
SIGHUP.
.SH OPTIONS
Command line options override configurations defined in
configuration file.
.TP 
\fB\*(T<\fB\-v | \-V | \-\-version\fR\*(T> \fR
Prints version and exits 

.TP 
\fB\*(T<\fB\-q | \-\-quiet\fR\*(T> \fR
Run Conky in 'quiet mode' (ie. no output) 

.TP 
\fB\*(T<\fB\-D | \-\-debug\fR\*(T> \fR
Increase debugging output, ie. -DD for more
debugging 

.TP 
\fB\*(T<\fB\-a | \-\-alignment=\fR\*(T> \fR\*(T<\fBALIGNMENT\fR\*(T> 
Text alignment on screen,
{top,bottom,middle}_{left,right,middle} or none. Can also
be abbreviated with first chars of position, ie. tr for
top_right. 

.TP 
\fB\*(T<\fB\-b | \-\-double\-buffer\fR\*(T> \fR
Use double buffering (eliminates "flicker") 

.TP 
\fB\*(T<\fB\-c | \-\-config=\fR\*(T> \fR\*(T<\fBFILE\fR\*(T> 
Config file to load instead of $HOME/.conkyrc 

.TP 
\fB\*(T<\fB\-C | \-\-print\-config\fR\*(T> \fR
Print builtin default config to stdout. See also
the section EXAMPLES for more information. 

.TP 
\fB\*(T<\fB\-d | \-\-daemonize\fR\*(T> \fR
Daemonize Conky, aka fork to background 

.TP 
\fB\*(T<\fB\-f | \-\-font=\fR\*(T> \fR\*(T<\fBFONT\fR\*(T> 
Font to use 

.TP 
\fB\*(T<\fB\-h | \-\-help\fR\*(T> \fR
Prints command line help and exits 

.TP 
\fB\*(T<\fB\-o | \-\-own\-window\fR\*(T> \fR
Create own window to draw 

.TP 
\fB\*(T<\fB\-t | \-\-text=\fR\*(T> \fR\*(T<\fBTEXT\fR\*(T> 
Text to render, remember single quotes, like -t '
$uptime ' 

.TP 
\fB\*(T<\fB\-p | \-\-pause=\fR\*(T> \fR\*(T<\fBSECONDS\fR\*(T> 
Time to pause before actually starting Conky

.TP 
\fB\*(T<\fB\-u | \-\-interval=\fR\*(T> \fR\*(T<\fBSECONDS\fR\*(T> 
Update interval 

.TP 
\fB\*(T<\fB\-w | \-\-window\-id=\fR\*(T> \fR\*(T<\fBWIN_ID\fR\*(T> 
Window id to draw 

.TP 
\fB\*(T<\fB\-X | \-\-display=\fR\*(T> \fR\*(T<\fBDISPLAY\fR\*(T> 
X11 display to use 

.TP 
\fB\*(T<\fB\-x\fR\*(T> \fR\*(T<\fBX_COORDINATE\fR\*(T> 
X position 

.TP 
\fB\*(T<\fB\-y\fR\*(T> \fR\*(T<\fBY_COORDINATE\fR\*(T> 
Y position 

.TP 
\fB\*(T<\fB\-i\fR\*(T> \fR\*(T<\fBCOUNT\fR\*(T> 
Number of times to update Conky (and quit) 

.SH "CONFIGURATION SETTINGS"
Default configuration file location is $HOME/.conkyrc or
${sysconfdir}/conky/conky.conf. On most systems, sysconfdir is
/etc, and you can find the sample config file there
(/etc/conky/conky.conf).
.PP
You might want to copy it to $HOME/.conkyrc and then
start modifying it. Other configs can be found at
http://conky.sf.net/
.TP 
\fB\*(T<\fBTEXT\fR\*(T> \fR
After this begins text to be formatted on screen.
Backslash (\e) escapes newlines in the text section. This
can be useful for cleaning up config files where conky is
used to pipe input to dzen2. 

.TP 
\fB\*(T<\fBalignment\fR\*(T> \fR
Aligned position on screen, may be top_left,
top_right, top_middle, bottom_left, bottom_right,
bottom_middle, middle_left, middle_middle, middle_right, or
none (also can be abreviated as tl, tr, tm, bl, br, bm, ml,
mm, mr). See also gap_x and gap_y.

.TP 
\fB\*(T<\fBappend_file\fR\*(T> \fR
Append the file given as argument. 

.TP 
\fB\*(T<\fBbackground\fR\*(T> \fR
Boolean value, if true, Conky will be forked to
background when started. 

.TP 
\fB\*(T<\fBborder_inner_margin\fR\*(T> \fR
Inner border margin in pixels (the margin between
the border and text). 

.TP 
\fB\*(T<\fBborder_outer_margin\fR\*(T> \fR
Outer border margin in pixels (the margin between
the border and the edge of the window). 

.TP 
\fB\*(T<\fBborder_width\fR\*(T> \fR
Border width in pixels. 

.TP 
\fB\*(T<\fBcolorN\fR\*(T> \fR
Predefine a color for use inside TEXT segments.
Substitute N by a digit between 0 and 9, inclusively. When
specifying the color value in hex, omit the leading hash
(#). 

.TP 
\fB\*(T<\fBcpu_avg_samples\fR\*(T> \fR
The number of samples to average for CPU
monitoring. 

.TP 
\fB\*(T<\fBdefault_bar_size\fR\*(T> \fR
Specify a default width and height for bars.
Example: 'default_bar_size 0 6'. This is particularly
useful for execbar and execibar as they do not take size
arguments. 

.TP 
\fB\*(T<\fBdefault_color\fR\*(T> \fR
Default color and border color 

.TP 
\fB\*(T<\fBdefault_gauge_size\fR\*(T> \fR
Specify a default width and height for gauges.
Example: 'default_gauge_size 25 25'. This is particularly
useful for execgauge and execigauge as they do not take
size arguments 

.TP 
\fB\*(T<\fBdefault_graph_size\fR\*(T> \fR
Specify a default width and height for graphs.
Example: 'default_graph_size 0 25'. This is particularly
useful for execgraph and execigraph as they do not take
size arguments 

.TP 
\fB\*(T<\fBdefault_outline_color\fR\*(T> \fR
Default outline color 

.TP 
\fB\*(T<\fBdefault_shade_color\fR\*(T> \fR
Default shading color and border's shading color 

.TP 
\fB\*(T<\fBdisable_auto_reload\fR\*(T> \fR
Enable to disable the inotify-based auto config reload feature.

.TP 
\fB\*(T<\fBdiskio_avg_samples\fR\*(T> \fR
The number of samples to average for disk I/O
monitoring. 

.TP 
\fB\*(T<\fBdisplay\fR\*(T> \fR
Specify an X display to connect to. 

.TP 
\fB\*(T<\fBdouble_buffer\fR\*(T> \fR
Use the Xdbe extension? (eliminates flicker) It
is highly recommended to use own window with this one so
double buffer won't be so big. 

.TP 
\fB\*(T<\fBdraw_borders\fR\*(T> \fR
Draw borders around text? 

.TP 
\fB\*(T<\fBdraw_graph_borders\fR\*(T> \fR
Draw borders around graphs? 

.TP 
\fB\*(T<\fBdraw_outline\fR\*(T> \fR
Draw outlines? 

.TP 
\fB\*(T<\fBdraw_shades\fR\*(T> \fR
Draw shades? 

.TP 
\fB\*(T<\fBextra_newline\fR\*(T> \fR
Put an extra newline at the end when writing to
stdout, useful for writing to awesome's wiboxes. 

.TP 
\fB\*(T<\fBfont\fR\*(T> \fR
Font name in X, xfontsel can be used to get a
nice font 

.TP 
\fB\*(T<\fBformat_human_readable\fR\*(T> \fR
If enabled, values which are in bytes will be
printed in human readable format (i.e., KiB, MiB, etc). If
disabled, the number of bytes is printed instead. 

.TP 
\fB\*(T<\fBgap_x\fR\*(T> \fR
Gap, in pixels, between right or left border of
screen, same as passing -x at command line, e.g. gap_x 10.
For other position related stuff, see 'alignment'. 

.TP 
\fB\*(T<\fBgap_y\fR\*(T> \fR
Gap, in pixels, between top or bottom border of
screen, same as passing -y at command line, e.g. gap_y 10.
For other position related stuff, see 'alignment'. 

.TP 
\fB\*(T<\fBhddtemp_host\fR\*(T> \fR
Hostname to connect to for hddtemp objects. Defaults
to "127.0.0.1".

.TP 
\fB\*(T<\fBhddtemp_port\fR\*(T> \fR
Port to use for hddtemp connections. Defaults to
7634.

.TP 
\fB\*(T<\fBif_up_strictness\fR\*(T> \fR
How strict should if_up be when testing an
interface for being up? The value is one of up, link or
address, to check for the interface being solely up, being
up and having link or being up, having link and an assigned
IP address. 

.TP 
\fB\*(T<\fBimap\fR\*(T> \fR
Default global IMAP server. Arguments are: "host
user pass [-i interval (in seconds)] [-f 'folder'] [-p port]
[-e 'command'] [-r retries]". Default port is 143, default
folder is 'INBOX', default interval is 5 minutes, and
default number of retries before giving up is 5. If the
password is supplied as '*', you will be prompted to enter
the password when Conky starts. 

.TP 
\fB\*(T<\fBimlib_cache_flush_interval\fR\*(T> \fR
Interval (in seconds) to flush Imlib2 cache. 

.TP 
\fB\*(T<\fBimlib_cache_size\fR\*(T> \fR
Imlib2 image cache size, in bytes. Defaults to
4MiB. Increase this value if you use $image lots. Set
to 0 to disable the image cache.

.TP 
\fB\*(T<\fBlua_draw_hook_post\fR\*(T> \fR\*(T<\fBfunction_name [function arguments]\fR\*(T> 
This function, if defined, will be called by
Conky through each iteration after drawing to the
window. Requires X support. Takes any number of
optional arguments. Use this hook for drawing things on
top of what Conky draws. Conky puts 'conky_' in front
of function_name to prevent accidental calls to the
wrong function unless you place 'conky_' in front of it
yourself.

.TP 
\fB\*(T<\fBlua_draw_hook_pre\fR\*(T> \fR\*(T<\fBfunction_name [function arguments]\fR\*(T> 
This function, if defined, will be called by
Conky through each iteration before drawing to the
window. Requires X support. Takes any number of
optional arguments. Use this hook for drawing things on
top of what Conky draws. Conky puts 'conky_' in front
of function_name to prevent accidental calls to the
wrong function unless you place 'conky_' in front of it
yourself.

.TP 
\fB\*(T<\fBlua_load\fR\*(T> \fR
Loads the Lua scripts separated by spaces. 

.TP 
\fB\*(T<\fBlua_shutdown_hook\fR\*(T> \fR\*(T<\fBfunction_name [function arguments]\fR\*(T> 
This function, if defined, will be called by
Conky at shutdown or when the configuration is
reloaded. Use this hook to clean up after yourself,
such as freeing memory which has been allocated by
external libraries via Lua. Conky puts 'conky_' in
front of function_name to prevent accidental calls to
the wrong function unless you place 'conky_' in
front of it yourself.

.TP 
\fB\*(T<\fBlua_startup_hook\fR\*(T> \fR\*(T<\fBfunction_name [function arguments]\fR\*(T> 
This function, if defined, will be called by
Conky at startup or when the configuration is reloaded.
Use this hook to initialize values, or for any run-once
applications. Conky puts 'conky_' in front of
function_name to prevent accidental calls to the wrong
function unless you place 'conky_' in front of
it yourself.

.TP 
\fB\*(T<\fBmail_spool\fR\*(T> \fR
Mail spool for mail checking 

.TP 
\fB\*(T<\fBmax_port_monitor_connections\fR\*(T> \fR
Allow each port monitor to track at most this
many connections (if 0 or not set, default is 256) 

.TP 
\fB\*(T<\fBmax_specials\fR\*(T> \fR
Maximum number of special things, e.g. fonts,
offsets, aligns, etc. (default is 512) 

.TP 
\fB\*(T<\fBmax_text_width\fR\*(T> \fR\*(T<\fBwidth\fR\*(T> 
When a line in the output contains 'width'
chars and the end isn't reached, the next char will start
on a new line. If you want to make sure that lines don't
get broken, set 'width' to 0

.TP 
\fB\*(T<\fBmax_user_text\fR\*(T> \fR\*(T<\fBbytes\fR\*(T> 
Maximum size of user text buffer, i.e. layout
below TEXT line in config file (default is 16384 bytes) 

.TP 
\fB\*(T<\fBmaximum_width\fR\*(T> \fR\*(T<\fBpixels\fR\*(T> 
Maximum width of window 

.TP 
\fB\*(T<\fBminimum_size\fR\*(T> \fR\*(T<\fBwidth (height)\fR\*(T> 
Minimum size of window 

.TP 
\fB\*(T<\fBmpd_host\fR\*(T> \fR
Host of MPD server 

.TP 
\fB\*(T<\fBmpd_password\fR\*(T> \fR
MPD server password 

.TP 
\fB\*(T<\fBmpd_port\fR\*(T> \fR
Port of MPD server 

.TP 
\fB\*(T<\fBmusic_player_interval\fR\*(T> \fR
Music player thread update interval (defaults to
Conky's update interval) 

.TP 
\fB\*(T<\fBnet_avg_samples\fR\*(T> \fR
The number of samples to average for net data 

.TP 
\fB\*(T<\fBno_buffers\fR\*(T> \fR
Subtract (file system) buffers from used memory?

.TP 
\fB\*(T<\fBnvidia_display\fR\*(T> \fR
The display that the nvidia variable will use (defaults to the value of the
display variable)

.TP 
\fB\*(T<\fBout_to_console\fR\*(T> \fR
Print text to stdout. 

.TP 
\fB\*(T<\fBout_to_ncurses\fR\*(T> \fR
Print text in the console, but use ncurses so
that conky can print the text of a new update over the old
text. (In the future this will provide more useful things) 

.TP 
\fB\*(T<\fBout_to_stderr\fR\*(T> \fR
Print text to stderr. 

.TP 
\fB\*(T<\fBout_to_x\fR\*(T> \fR
When set to no, there will be no output in X
(useful when you also use things like out_to_console). If
you set it to no, make sure that it's placed before all
other X-related setting (take the first line of your
configfile to be sure). Default value is yes 

.TP 
\fB\*(T<\fBoverride_utf8_locale\fR\*(T> \fR
Force UTF8? requires XFT 

.TP 
\fB\*(T<\fBoverwrite_file\fR\*(T> \fR
Overwrite the file given as argument. 

.TP 
\fB\*(T<\fBown_window\fR\*(T> \fR
Boolean, create own window to draw? 

.TP 
\fB\*(T<\fBown_window_class\fR\*(T> \fR
Manually set the WM_CLASS name. Defaults to
"Conky". 

.TP 
\fB\*(T<\fBown_window_colour\fR\*(T> \fR\*(T<\fBcolour\fR\*(T> 
If own_window_transparent no, set a specified
background colour (defaults to black). Takes either a hex
value (e.g. ffffff, note the lack of '#') or a valid RGB
name (see /usr/lib/X11/rgb.txt)

.TP 
\fB\*(T<\fBown_window_hints\fR\*(T> \fR\*(T<\fBundecorated,below,above,sticky,skip_taskbar,skip_pager\fR\*(T> 
If own_window is yes, you may use these window
manager hints to affect the way Conky displays. Notes: Use
own_window_type desktop as another way to implement many of
these hints implicitly. If you use own_window_type
override, window manager hints have no meaning and are
ignored. 

.TP 
\fB\*(T<\fBown_window_title\fR\*(T> \fR
Manually set the window name. Defaults to
"<hostname> - conky". 

.TP 
\fB\*(T<\fBown_window_argb_visual\fR\*(T> \fR
Boolean, use ARGB visual? ARGB can be used for real
transparency, note that a composite manager is required for real
transparency. This option will not work as desired (in most cases)
in conjunction with 'own_window_type override'.

.TP 
\fB\*(T<\fBown_window_argb_value\fR\*(T> \fR
When ARGB visuals are enabled, this use this to modify the alpha value used. Valid range is 0-255, where 0 is 0% opacity, and 255 is 100% opacity.

.TP 
\fB\*(T<\fBown_window_transparent\fR\*(T> \fR
Boolean, set transparency? If ARGB visual is enabled, sets
background opacity to 0%.

.TP 
\fB\*(T<\fBown_window_type\fR\*(T> \fR
if own_window is yes, you may specify type
normal, desktop, dock, panel or override (default: normal).
Desktop windows are special windows that have no window
decorations; are always visible on your desktop; do not
appear in your pager or taskbar; and are sticky across all
workspaces. Panel windows reserve space along a desktop
edge, just like panels and taskbars, preventing maximized
windows from overlapping them. The edge is chosen based on
the alignment option. Override windows are not under the
control of the window manager. Hints are ignored. This type
of window can be useful for certain situations. 

.TP 
\fB\*(T<\fBpad_percents\fR\*(T> \fR
Pad percentages to this many decimals (0 = no
padding) 

.TP 
\fB\*(T<\fBpop3\fR\*(T> \fR
Default global POP3 server. Arguments are: "host
user pass [-i interval (in seconds)] [-p port] [-e 'command']
[-r retries]". Default port is 110, default interval is 5
minutes, and default number of retries before giving up is
5. If the password is supplied as '*', you will be prompted
to enter the password when Conky starts. 

.TP 
\fB\*(T<\fBshort_units\fR\*(T> \fR
Shortens units to a single character (kiB->k,
GiB->G, etc.). Default is off. 

.TP 
\fB\*(T<\fBshow_graph_range\fR\*(T> \fR
Shows the time range covered by a graph. 

.TP 
\fB\*(T<\fBshow_graph_scale\fR\*(T> \fR
Shows the maximum value in scaled graphs. 

.TP 
\fB\*(T<\fBstippled_borders\fR\*(T> \fR
Border stippling (dashing) in pixels 

.TP 
\fB\*(T<\fBtemperature_unit\fR\*(T> \fR
Desired output unit of all objects displaying a
temperature. Parameters are either "fahrenheit" or
"celsius". The default unit is degree Celsius. 

.TP 
\fB\*(T<\fBtemplateN\fR\*(T> \fR
Define a template for later use inside TEXT
segments. Substitute N by a digit between 0 and 9,
inclusively. The value of the variable is being inserted
into the stuff below TEXT at the corresponding position,
but before some substitutions are applied: 

\&'\en' -> newline
.br
\&'\e\e' -> backslash
.br
\&'\e ' -> space
.br
\&'\eN' -> template argument N

.TP 
\fB\*(T<\fBtext_buffer_size\fR\*(T> \fR\*(T<\fBbytes\fR\*(T> 
Size of the standard text buffer (default is 256
bytes). This buffer is used for intermediary text, such as
individual lines, output from $exec vars, and various other
variables. Increasing the size of this buffer can
drastically reduce Conky's performance, but will allow for
more text display per variable. The size of this buffer
cannot be smaller than the default value of 256 bytes. 

.TP 
\fB\*(T<\fBtimes_in_seconds\fR\*(T> \fR
If true, variables that output times output a number
that represents seconds. This doesn't affect $time, $tztime and
$utime

.TP 
\fB\*(T<\fBtop_cpu_separate\fR\*(T> \fR
If true, cpu in top will show usage of one
processor's power. If false, cpu in top will show the usage
of all processors' power combined. 

.TP 
\fB\*(T<\fBtop_name_width\fR\*(T> \fR
Width for $top name value (defaults to 15
characters). 

.TP 
\fB\*(T<\fBtotal_run_times\fR\*(T> \fR
Total number of times for Conky to update before
quitting. Zero makes Conky run forever 

.TP 
\fB\*(T<\fBupdate_interval\fR\*(T> \fR\*(T<\fBseconds\fR\*(T> 
Update interval 

.TP 
\fB\*(T<\fBupdate_interval_on_battery\fR\*(T> \fR\*(T<\fBseconds\fR\*(T> 
Update interval when running on batterypower 

.TP 
\fB\*(T<\fBuppercase\fR\*(T> \fR
Boolean value, if true, text is rendered in upper
case 

.TP 
\fB\*(T<\fBuse_spacer\fR\*(T> \fR
Adds spaces around certain objects to stop them
from moving other things around. Arguments are left, right,
and none (default). The old true/false values are
deprecated and default to right/none respectively. Note
that this only helps if you are using a mono font, such as
Bitstream Vera Sans Mono. 

.TP 
\fB\*(T<\fBuse_xft\fR\*(T> \fR
Use Xft (anti-aliased font and stuff) 

.TP 
\fB\*(T<\fBxftalpha\fR\*(T> \fR
Alpha of Xft font. Must be a value at or between
1 and 0. 

.TP 
\fB\*(T<\fBxftfont\fR\*(T> \fR
Xft font to use. 

.SH OBJECTS/VARIABLES
Colours are parsed using XParsecolor(), there might be a
list of them: /usr/share/X11/rgb.txt. 
Colour can be also in
#rrggbb format (hex).
.PP
Some objects may create threads, and sometimes these threads will
not be destroyed until Conky terminates. There is no way to
destroy or clean up threads while Conky is running. For example,
if you use an MPD variable, the MPD thread will keep running until
Conky dies. Some threaded objects will use one of the parameters
as a 'key', so that you only have 1 relevant thread running (for
example, the $curl, $rss and $weather objects launch one thread per
URI).
.TP 
\fB\*(T<\fBacpiacadapter\fR\*(T> \fR\*(T<\fB(adapter)\fR\*(T> 
ACPI ac adapter state. On linux, the adapter option specifies the
subfolder of /sys/class/power_supply containing the state information (tries "AC"
and "ADP1" if there is no argument given). Non-linux systems ignore it.

.TP 
\fB\*(T<\fBacpifan\fR\*(T> \fR
ACPI fan state 

.TP 
\fB\*(T<\fBacpitemp\fR\*(T> \fR
ACPI temperature in C. 

.TP 
\fB\*(T<\fBaddr\fR\*(T> \fR\*(T<\fB(interface)\fR\*(T> 
IP address for an interface, or "No Address" if
no address is assigned. 

.TP 
\fB\*(T<\fBaddrs\fR\*(T> \fR\*(T<\fB(interface)\fR\*(T> 
IP addresses for an interface (if one - works
like addr). Linux only. 

.TP 
\fB\*(T<\fBadt746xcpu\fR\*(T> \fR
CPU temperature from therm_adt746x 

.TP 
\fB\*(T<\fBadt746xfan\fR\*(T> \fR
Fan speed from therm_adt746x 

.TP 
\fB\*(T<\fBalignc\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Align text to centre 

.TP 
\fB\*(T<\fBalignr\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Right-justify text, with space of N 

.TP 
\fB\*(T<\fBapcupsd\fR\*(T> \fR\*(T<\fBhost\fR\*(T> \*(T<\fBport\fR\*(T> 
Sets up the connection to apcupsd daemon. Prints
nothing, defaults to localhost:3551 

.TP 
\fB\*(T<\fBapcupsd_cable\fR\*(T> \fR
Prints the UPS connection type. 

.TP 
\fB\*(T<\fBapcupsd_charge\fR\*(T> \fR
Current battery capacity in percent. 

.TP 
\fB\*(T<\fBapcupsd_lastxfer\fR\*(T> \fR
Reason for last transfer from line to battery. 

.TP 
\fB\*(T<\fBapcupsd_linev\fR\*(T> \fR
Nominal input voltage. 

.TP 
\fB\*(T<\fBapcupsd_load\fR\*(T> \fR
Current load in percent. 

.TP 
\fB\*(T<\fBapcupsd_loadbar\fR\*(T> \fR
Bar showing current load. 

.TP 
\fB\*(T<\fBapcupsd_loadgauge\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Gauge that shows current load. 

.TP 
\fB\*(T<\fBapcupsd_loadgraph\fR\*(T> \fR\*(T<\fB(height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
History graph of current load. 

.TP 
\fB\*(T<\fBapcupsd_model\fR\*(T> \fR
Prints the model of the UPS. 

.TP 
\fB\*(T<\fBapcupsd_name\fR\*(T> \fR
Prints the UPS user-defined name. 

.TP 
\fB\*(T<\fBapcupsd_status\fR\*(T> \fR
Prints current status (on-line, on-battery). 

.TP 
\fB\*(T<\fBapcupsd_temp\fR\*(T> \fR
Current internal temperature. 

.TP 
\fB\*(T<\fBapcupsd_timeleft\fR\*(T> \fR
Time left to run on battery. 

.TP 
\fB\*(T<\fBapcupsd_upsmode\fR\*(T> \fR
Prints the UPS mode (e.g. standalone). 

.TP 
\fB\*(T<\fBapm_adapter\fR\*(T> \fR
Display APM AC adapter status (FreeBSD only) 

.TP 
\fB\*(T<\fBapm_battery_life\fR\*(T> \fR
Display APM battery life in percent (FreeBSD
only) 

.TP 
\fB\*(T<\fBapm_battery_time\fR\*(T> \fR
Display remaining APM battery life in hh:mm:ss or
"unknown" if AC adapterstatus is on-line or charging
(FreeBSD only) 

.TP 
\fB\*(T<\fBaudacious_bar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Progress bar 

.TP 
\fB\*(T<\fBaudacious_bitrate\fR\*(T> \fR
Bitrate of current tune 

.TP 
\fB\*(T<\fBaudacious_channels\fR\*(T> \fR
Number of audio channels of current tune 

.TP 
\fB\*(T<\fBaudacious_filename\fR\*(T> \fR
Full path and filename of current tune 

.TP 
\fB\*(T<\fBaudacious_frequency\fR\*(T> \fR
Sampling frequency of current tune 

.TP 
\fB\*(T<\fBaudacious_length\fR\*(T> \fR
Total length of current tune as MM:SS 

.TP 
\fB\*(T<\fBaudacious_length_seconds\fR\*(T> \fR
Total length of current tune in seconds 

.TP 
\fB\*(T<\fBaudacious_main_volume\fR\*(T> \fR
The current volume fetched from Audacious 

.TP 
\fB\*(T<\fBaudacious_playlist_length\fR\*(T> \fR
Number of tunes in playlist 

.TP 
\fB\*(T<\fBaudacious_playlist_position\fR\*(T> \fR
Playlist position of current tune 

.TP 
\fB\*(T<\fBaudacious_position\fR\*(T> \fR
Position of current tune (MM:SS) 

.TP 
\fB\*(T<\fBaudacious_position_seconds\fR\*(T> \fR
Position of current tune in seconds 

.TP 
\fB\*(T<\fBaudacious_status\fR\*(T> \fR
Player status (Playing/Paused/Stopped/Not
running) 

.TP 
\fB\*(T<\fBaudacious_title\fR\*(T> \fR\*(T<\fB(max length)\fR\*(T> 
Title of current tune with optional maximum
length specifier 

.TP 
\fB\*(T<\fBbattery\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Battery status and remaining percentage capacity
of ACPI or APM battery. ACPI battery number can be given as
argument (default is BAT0). 

.TP 
\fB\*(T<\fBbattery_bar\fR\*(T> \fR\*(T<\fB(height),(width) (num)\fR\*(T> 
Battery percentage remaining of ACPI battery in a
bar. ACPI battery number can be given as argument (default
is BAT0). 

.TP 
\fB\*(T<\fBbattery_percent\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Battery percentage remaining for ACPI battery.
ACPI battery number can be given as argument (default is
BAT0). 

.TP 
\fB\*(T<\fBbattery_short\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Battery status and remaining percentage capacity
of ACPI or APM battery. ACPI battery number can be given as
argument (default is BAT0). This mode display a short
status, which means that C is displayed instead of
charging, D for discharging, F for full, N for not present,
E for empty and U for unknown. 

.TP 
\fB\*(T<\fBbattery_time\fR\*(T> \fR\*(T<\fB(num)\fR\*(T> 
Battery charge/discharge time remaining of ACPI
battery. ACPI battery number can be given as argument
(default is BAT0). 

.TP 
\fB\*(T<\fBblink\fR\*(T> \fR\*(T<\fBtext_and_other_conky_vars\fR\*(T> 
Let 'text_and_other_conky_vars' blink on and off.

.TP 
\fB\*(T<\fBbmpx_album\fR\*(T> \fR
Album in current BMPx track 

.TP 
\fB\*(T<\fBbmpx_artist\fR\*(T> \fR
Artist in current BMPx track 

.TP 
\fB\*(T<\fBbmpx_bitrate\fR\*(T> \fR
Bitrate of the current BMPx track 

.TP 
\fB\*(T<\fBbmpx_title\fR\*(T> \fR
Title of the current BMPx track 

.TP 
\fB\*(T<\fBbmpx_track\fR\*(T> \fR
Track number of the current BMPx track 

.TP 
\fB\*(T<\fBbmpx_uri\fR\*(T> \fR
URI of the current BMPx track 

.TP 
\fB\*(T<\fBbuffers\fR\*(T> \fR
Amount of memory buffered 

.TP 
\fB\*(T<\fBcached\fR\*(T> \fR
Amount of memory cached 

.TP 
\fB\*(T<\fBcmdline_to_pid\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
PID of the first process that has string in it's
commandline

.TP 
\fB\*(T<\fBcolor\fR\*(T> \fR\*(T<\fB(color)\fR\*(T> 
Change drawing color to 'color' which is a name of
a color or a hexcode preceded with # (for example #0A1B2C ).
If you use ncurses only the following colors are supported:
red,green,yellow,blue,magenta,cyan,black,white.

.TP 
\fB\*(T<\fBcolorN\fR\*(T> \fR
Change drawing color to colorN configuration
option, where N is a digit between 0 and 9, inclusively. 

.TP 
\fB\*(T<\fBcombine\fR\*(T> \fR\*(T<\fBvar1 var2\fR\*(T> 
Places the lines of var2 to the right of the
lines of var1 separated by the chars that are put between
var1 and var2. For example: ${combine ${head /proc/cpuinfo
2} - ${head /proc/meminfo 1}} gives as output
"cpuinfo_line1 - meminfo_line1" on line 1 and
"cpuinfo_line2 -" on line 2. $combine vars can also be
nested to place more vars next to each other. 

.TP 
\fB\*(T<\fBconky_build_arch\fR\*(T> \fR
CPU architecture Conky was built for 

.TP 
\fB\*(T<\fBconky_build_date\fR\*(T> \fR
Date Conky was built 

.TP 
\fB\*(T<\fBconky_version\fR\*(T> \fR
Conky version 

.TP 
\fB\*(T<\fBcpu\fR\*(T> \fR\*(T<\fB(cpuN)\fR\*(T> 
CPU usage in percents. For SMP machines, the CPU
number can be provided as an argument. ${cpu cpu0} is the
total usage, and ${cpu cpuX} (X >= 1) are individual
CPUs. 

.TP 
\fB\*(T<\fBcpubar\fR\*(T> \fR\*(T<\fB(cpuN) (height),(width)\fR\*(T> 
Bar that shows CPU usage, height is bar's height
in pixels. See $cpu for more info on SMP. 

.TP 
\fB\*(T<\fBcpugauge\fR\*(T> \fR\*(T<\fB(cpuN) (height),(width)\fR\*(T> 
Elliptical gauge that shows CPU usage, height and
width are gauge's vertical and horizontal axis
respectively. See $cpu for more info on SMP. 

.TP 
\fB\*(T<\fBcpugraph\fR\*(T> \fR\*(T<\fB(cpuN) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
CPU usage graph, with optional colours in hex,
minus the #. See $cpu for more info on SMP. Uses a
logarithmic scale (to see small numbers) when you use the
-l switch. Takes the switch '-t' to use a temperature
gradient, which makes the gradient values change depending
on the amplitude of a particular graph value (try it and
see). 

.TP 
\fB\*(T<\fBcurl\fR\*(T> \fR\*(T<\fBurl (interval_in_minutes)\fR\*(T> 
Download data from URI using Curl at the
specified interval. The interval may be a floating
point value greater than 0, otherwise defaults to 15
minutes. Most useful when used in conjunction with Lua
and the Lua API. This object is threaded, and once a
thread is created it can't be explicitly destroyed.
One thread will run for each URI specified. You can use
any protocol that Curl supports.
.TP 
\fB\*(T<\fBdesktop\fR\*(T> \fR
Number of the desktop on which conky is running
or the message "Not running in X" if this is the case. 

.TP 
\fB\*(T<\fBdesktop_name\fR\*(T> \fR
Name of the desktop on which conky is running or
the message "Not running in X" if this is the case. 

.TP 
\fB\*(T<\fBdesktop_number\fR\*(T> \fR
Number of desktops or the message "Not running in
X" if this is the case. 

.TP 
\fB\*(T<\fBdisk_protect\fR\*(T> \fR\*(T<\fBdevice\fR\*(T> 
Disk protection status, if supported (needs
kernel-patch). Prints either "frozen" or "free " (note the
padding). 

.TP 
\fB\*(T<\fBdiskio\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays current disk IO. Device is optional, and
takes the form of sda for /dev/sda. Individual partitions
are allowed. 

.TP 
\fB\*(T<\fBdiskio_read\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays current disk IO for reads. Device as in
diskio. 

.TP 
\fB\*(T<\fBdiskio_write\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays current disk IO for writes. Device as in
diskio. 

.TP 
\fB\*(T<\fBdiskiograph\fR\*(T> \fR\*(T<\fB(device) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Disk IO graph, colours defined in hex, minus the
#. If scale is non-zero, it becomes the scale for the
graph. Uses a logarithmic scale (to see small numbers) when
you use -l switch. Takes the switch '-t' to use a
temperature gradient, which makes the gradient values
change depending on the amplitude of a particular graph
value (try it and see). 

.TP 
\fB\*(T<\fBdiskiograph_read\fR\*(T> \fR\*(T<\fB(device) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Disk IO graph for reads, colours defined in hex,
minus the #. If scale is non-zero, it becomes the scale for
the graph. Device as in diskio. Uses a logarithmic scale
(to see small numbers) when you use -l switch. Takes the
switch '-t' to use a temperature gradient, which makes the
gradient values change depending on the amplitude of a
particular graph value (try it and see). 

.TP 
\fB\*(T<\fBdiskiograph_write\fR\*(T> \fR\*(T<\fB(device) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Disk IO graph for writes, colours defined in hex,
minus the #. If scale is non-zero, it becomes the scale for
the graph. Device as in diskio. Uses a logarithmic scale
(to see small numbers) when you use -l switch. Takes the
switch '-t' to use a temperature gradient, which makes the
gradient values change depending on the amplitude of a
particular graph value (try it and see). 

.TP 
\fB\*(T<\fBdownspeed\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Download speed in suitable IEC units 

.TP 
\fB\*(T<\fBdownspeedf\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Download speed in KiB with one decimal 

.TP 
\fB\*(T<\fBdownspeedgraph\fR\*(T> \fR\*(T<\fB(netdev) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Download speed graph, colours defined in hex,
minus the #. If scale is non-zero, it becomes the scale for
the graph. Uses a logarithmic scale (to see small numbers)
when you use -l switch. Takes the switch '-t' to use a
temperature gradient, which makes the gradient values
change depending on the amplitude of a particular graph
value (try it and see). 

.TP 
\fB\*(T<\fBdraft_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as draft in the specified
mailbox or mail spool if not. Only maildir type mailboxes
are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBelse\fR\*(T> \fR
Text to show if any of the above are not true 

.TP 
\fB\*(T<\fBendif\fR\*(T> \fR
Ends an $if block. 

.TP 
\fB\*(T<\fBentropy_avail\fR\*(T> \fR
Current entropy available for crypto freaks 

.TP 
\fB\*(T<\fBentropy_bar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Normalized bar of available entropy for crypto
freaks 

.TP 
\fB\*(T<\fBentropy_perc\fR\*(T> \fR
Percentage of entropy available in comparison to
the poolsize 

.TP 
\fB\*(T<\fBentropy_poolsize\fR\*(T> \fR
Total size of system entropy pool for crypto
freaks 

.TP 
\fB\*(T<\fBeval\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
Evaluates given string according to the rules of
TEXT interpretation, i.e. parsing any contained text object
specifications into their output, any occuring '$$' into a
single '$' and so on. The output is then being parsed
again. 

.TP 
\fB\*(T<\fBeve\fR\*(T> \fR\*(T<\fBapi_userid api_key character_id\fR\*(T> 
Fetches your currently training skill from the
Eve Online API servers (http://www.eve-online.com/) and
displays the skill along with the remaining training time. 

.TP 
\fB\*(T<\fBexec\fR\*(T> \fR\*(T<\fBcommand\fR\*(T> 
Executes a shell command and displays the output
in conky. warning: this takes a lot more resources than
other variables. I'd recommend coding wanted behaviour in C
and posting a patch. 

.TP 
\fB\*(T<\fBexecbar\fR\*(T> \fR\*(T<\fBcommand\fR\*(T> 
Same as exec, except if the first value return is
a value between 0-100, it will use that number for a bar.
The size for bars can be controlled via the
default_bar_size config setting. 

.TP 
\fB\*(T<\fBexecgauge\fR\*(T> \fR\*(T<\fBcommand\fR\*(T> 
Same as exec, except if the first value returned
is a value between 0-100, it will use that number for a
gauge. The size for gauges can be controlled via the
default_gauge_size config setting. 

.TP 
\fB\*(T<\fBexecgraph\fR\*(T> \fR\*(T<\fB(\-t) (\-l) command\fR\*(T> 
Same as execbar, but graphs values. Uses a
logaritmic scale when the log option (-l switch) is given
(to see small numbers). Values still have to be between 0
and 100. The size for graphs can be controlled via the
default_graph_size config setting. Takes the switch '-t' to
use a temperature gradient, which makes the gradient values
change depending on the amplitude of a particular graph
value (try it and see). If -t or -l is your first argument,
you may need to preceed it by a space (' ').

.TP 
\fB\*(T<\fBexeci\fR\*(T> \fR\*(T<\fBinterval command\fR\*(T> 
Same as exec but with specific interval. Interval
can't be less than update_interval in configuration. See
also $texeci

.TP 
\fB\*(T<\fBexecibar\fR\*(T> \fR\*(T<\fBinterval command\fR\*(T> 
Same as execbar, except with an interval 

.TP 
\fB\*(T<\fBexecigauge\fR\*(T> \fR\*(T<\fBinterval command\fR\*(T> 
Same as execgauge, but takes an interval arg and
gauges values. 

.TP 
\fB\*(T<\fBexecigraph\fR\*(T> \fR\*(T<\fBinterval (\-t) (\-l) command\fR\*(T> 
Same as execgraph, but takes an interval arg and
graphs values. If -t or -l is your first argument, you may
need to preceed it by a space (' '). 

.TP 
\fB\*(T<\fBexecp\fR\*(T> \fR\*(T<\fBcommand\fR\*(T> 
Executes a shell command and displays the output
in conky. warning: this takes a lot more resources than
other variables. I'd recommend coding wanted behaviour in C
and posting a patch. This differs from $exec in that it
parses the output of the command, so you can insert things
like ${color red}hi!${color} in your script and have it
correctly parsed by Conky. Caveats: Conky parses and
evaluates the output of $execp every time Conky loops, and
then destroys all the objects. If you try to use anything
like $execi within an $execp statement, it will
functionally run at the same interval that the $execp
statement runs, as it is created and destroyed at every
interval. 

.TP 
\fB\*(T<\fBexecpi\fR\*(T> \fR\*(T<\fBinterval command\fR\*(T> 
Same as execp but with specific interval.
Interval can't be less than update_interval in
configuration. Note that the output from the $execpi
command is still parsed and evaluated at every interval. 

.TP 
\fB\*(T<\fBflagged_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as flagged in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBfont\fR\*(T> \fR\*(T<\fB(font)\fR\*(T> 
Specify a different font. This new font will
apply to the current line and everything following. You can
use a $font with no arguments to change back to the default
font (much like with $color) 

.TP 
\fB\*(T<\fBformat_time\fR\*(T> \fR\*(T<\fBseconds format\fR\*(T> 
Format time given in seconds. This var only works when
the times_in_seconds configuration setting is on. Format is a string
that should start and end with a "-char. The "-chars are not
part of the output, \ew,\ed,\eh,\em,\es,\e(,\e) and \e\e are replaced by
weeks,days,hours,minutes,seconds,(,) and \e. If you leave out a unit,
it's value will be expressed in the highest unite lower then the
one left out. Text between ()-chars will not be visible if a
replaced unit in this text is 0. If seconds is a decimal number
then you can see the numbers behind the point by using \eS
followed by a number that specifies the amount of
digits behind the point that you want to see (maximum 9).
You can also place a 'x' behind \eS so you have all digits behind
the point and no trailing zero's. (also maximum 9)

.TP 
\fB\*(T<\fBforwarded_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as forwarded in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBfreq\fR\*(T> \fR\*(T<\fB(n)\fR\*(T> 
Returns CPU #n's frequency in MHz. CPUs are
counted from 1. If omitted, the parameter defaults to 1. 

.TP 
\fB\*(T<\fBfreq_g\fR\*(T> \fR\*(T<\fB(n)\fR\*(T> 
Returns CPU #n's frequency in GHz. CPUs are
counted from 1. If omitted, the parameter defaults to 1. 

.TP 
\fB\*(T<\fBfs_bar\fR\*(T> \fR\*(T<\fB(height),(width) fs\fR\*(T> 
Bar that shows how much space is used on a file
system. height is the height in pixels. fs is any file on
that file system. 

.TP 
\fB\*(T<\fBfs_bar_free\fR\*(T> \fR\*(T<\fB(height),(width) fs\fR\*(T> 
Bar that shows how much space is free on a file
system. height is the height in pixels. fs is any file on
that file system. 

.TP 
\fB\*(T<\fBfs_free\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
Free space on a file system available for users. 

.TP 
\fB\*(T<\fBfs_free_perc\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
Free percentage of space on a file system
available for users. 

.TP 
\fB\*(T<\fBfs_size\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
File system size. 

.TP 
\fB\*(T<\fBfs_type\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
File system type. 

.TP 
\fB\*(T<\fBfs_used\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
File system used space. 

.TP 
\fB\*(T<\fBfs_used_perc\fR\*(T> \fR\*(T<\fB(fs)\fR\*(T> 
Percent of file system used space. 

.TP 
\fB\*(T<\fBgoto\fR\*(T> \fR\*(T<\fBx\fR\*(T> 
The next element will be printed at position 'x'.

.TP 
\fB\*(T<\fBgw_iface\fR\*(T> \fR
Displays the default route's interface or
"multiple"/"none" accordingly. 

.TP 
\fB\*(T<\fBgw_ip\fR\*(T> \fR
Displays the default gateway's IP or
"multiple"/"none" accordingly. 

.TP 
\fB\*(T<\fBhddtemp\fR\*(T> \fR\*(T<\fB(dev)\fR\*(T> 
Displays temperature of a selected hard disk
drive as reported by the hddtemp daemon. Use hddtemp_host
and hddtemp_port to specify a host and port for all hddtemp
objects. If no dev parameter is given, the first disk returned
by the hddtemp daemon is used.

.TP 
\fB\*(T<\fBhead\fR\*(T> \fR\*(T<\fBlogfile lines (next_check)\fR\*(T> 
Displays first N lines of supplied text file. The
file is checked every 'next_check' update. If next_check is
not supplied, Conky defaults to 2. Max of 30 lines can be
displayed, or until the text buffer is filled. 

.TP 
\fB\*(T<\fBhr\fR\*(T> \fR\*(T<\fB(height)\fR\*(T> 
Horizontal line, height is the height in pixels 

.TP 
\fB\*(T<\fBhwmon\fR\*(T> \fR\*(T<\fB(dev) type n (factor offset)\fR\*(T> 
Hwmon sensor from sysfs (Linux 2.6). Parameter
dev may be omitted if you have only one hwmon device.
Parameter type is either 'in' or 'vol' meaning voltage;
\&'fan' meaning fan; 'temp' meaning temperature. Parameter n
is number of the sensor. See /sys/class/hwmon/ on your
local computer. The optional arguments 'factor' and
\&'offset' allow precalculation of the raw input, which is
being modified as follows: 'input = input * factor +
offset'. Note that they have to be given as decimal values
(i.e. contain at least one decimal place). 

.TP 
\fB\*(T<\fBi2c\fR\*(T> \fR\*(T<\fB(dev) type n (factor offset)\fR\*(T> 
I2C sensor from sysfs (Linux 2.6). Parameter dev
may be omitted if you have only one I2C device. Parameter
type is either 'in' or 'vol' meaning voltage; 'fan' meaning
fan; 'temp' meaning temperature. Parameter n is number of
the sensor. See /sys/bus/i2c/devices/ on your local
computer. The optional arguments 'factor' and 'offset'
allow precalculation of the raw input, which is being
modified as follows: 'input = input * factor + offset'.
Note that they have to be given as decimal values (i.e.
contain at least one decimal place). 

.TP 
\fB\*(T<\fBi8k_ac_status\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays whether ac power is on, as listed in
/proc/i8k (translated to human-readable). Beware that this
is by default not enabled by i8k itself. 

.TP 
\fB\*(T<\fBi8k_bios\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the bios version as listed in /proc/i8k. 

.TP 
\fB\*(T<\fBi8k_buttons_status\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the volume buttons status as listed in
/proc/i8k. 

.TP 
\fB\*(T<\fBi8k_cpu_temp\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the cpu temperature in Celsius, as
reported by /proc/i8k. 

.TP 
\fB\*(T<\fBi8k_left_fan_rpm\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the left fan's rate of rotation, in
revolutions per minute as listed in /proc/i8k. Beware, some
laptops i8k reports these fans in reverse order. 

.TP 
\fB\*(T<\fBi8k_left_fan_status\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the left fan status as listed in
/proc/i8k (translated to human-readable). Beware, some
laptops i8k reports these fans in reverse order. 

.TP 
\fB\*(T<\fBi8k_right_fan_rpm\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the right fan's rate of rotation, in
revolutions per minute as listed in /proc/i8k. Beware, some
laptops i8k reports these fans in reverse order. 

.TP 
\fB\*(T<\fBi8k_right_fan_status\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the right fan status as listed in
/proc/i8k (translated to human-readable). Beware, some
laptops i8k reports these fans in reverse order. 

.TP 
\fB\*(T<\fBi8k_serial\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays your laptop serial number as listed in
/proc/i8k. 

.TP 
\fB\*(T<\fBi8k_version\fR\*(T> \fR
If running the i8k kernel driver for Inspiron
laptops, displays the version formatting of /proc/i8k. 

.TP 
\fB\*(T<\fBibm_brightness\fR\*(T> \fR
If running the IBM ACPI, displays the brigtness
of the laptops's LCD (0-7). 

.TP 
\fB\*(T<\fBibm_fan\fR\*(T> \fR
If running the IBM ACPI, displays the fan speed. 

.TP 
\fB\*(T<\fBibm_temps\fR\*(T> \fR\*(T<\fBN\fR\*(T> 
If running the IBM ACPI, displays the
temperatures from the IBM temperature sensors (N=0..7)
Sensor 0 is on the CPU, 3 is on the GPU. 

.TP 
\fB\*(T<\fBibm_volume\fR\*(T> \fR
If running the IBM ACPI, displays the "master"
volume, controlled by the volume keys (0-14). 

.TP 
\fB\*(T<\fBiconv_start\fR\*(T> \fR\*(T<\fBcodeset_from codeset_to\fR\*(T> 
Convert text from one codeset to another using
GNU iconv. Needs to be stopped with iconv_stop. 

.TP 
\fB\*(T<\fBiconv_stop\fR\*(T> \fR
Stop iconv codeset conversion. 

.TP 
\fB\*(T<\fBif_empty\fR\*(T> \fR\*(T<\fB(var)\fR\*(T> 
if conky variable VAR is empty, display
everything between $if_empty and the matching $endif 

.TP 
\fB\*(T<\fBif_existing\fR\*(T> \fR\*(T<\fBfile (string)\fR\*(T> 
if FILE exists, display everything between
if_existing and the matching $endif. The optional second
parameter checks for FILE containing the specified string
and prints everything between $if_existing and the matching
$endif. 

.TP 
\fB\*(T<\fBif_gw\fR\*(T> \fR
if there is at least one default gateway, display
everything between $if_gw and the matching $endif 

.TP 
\fB\*(T<\fBif_match\fR\*(T> \fR\*(T<\fBexpression\fR\*(T> 
Evaluates the given boolean expression, printing
everything between $if_match and the matching $endif
depending on whether the evaluation returns true or not.
Valid expressions consist of a left side, an operator and a
right side. Left and right sides are being parsed for
contained text objects before evaluation. Recognised left
and right side types are: 

\fBdouble\fRArgument consists of only
digits and a single dot.
.br
\fBlong\fRArgument consists of only
digits.
.br
\fBstring\fRArgument is enclosed in
quotation marks (")

Valid operands are: '>', '<', '>=',
\&'<=', '==', '!='. 

.TP 
\fB\*(T<\fBif_mixer_mute\fR\*(T> \fR\*(T<\fB(mixer)\fR\*(T> 
If mixer exists, display everything between
$if_mixer_mute and the matching $endif. If no mixer is
specified, "Vol" is used. 

.TP 
\fB\*(T<\fBif_mounted\fR\*(T> \fR\*(T<\fB(mountpoint)\fR\*(T> 
if MOUNTPOINT is mounted, display everything
between $if_mounted and the matching $endif 

.TP 
\fB\*(T<\fBif_mpd_playing\fR\*(T> \fR
if mpd is playing or paused, display everything
between $if_mpd_playing and the matching $endif 

.TP 
\fB\*(T<\fBif_running\fR\*(T> \fR\*(T<\fB(process)\fR\*(T> 
if PROCESS is running, display everything
$if_running and the matching $endif. This uses the
``pidof'' command, so the -x switch is also supported. 

.TP 
\fB\*(T<\fBif_smapi_bat_installed\fR\*(T> \fR\*(T<\fB(INDEX)\fR\*(T> 
when using smapi, if the battery with index INDEX
is installed, display everything between
$if_smapi_bat_installed and the matching $endif 

.TP 
\fB\*(T<\fBif_up\fR\*(T> \fR\*(T<\fB(interface)\fR\*(T> 
if INTERFACE exists and is up, display everything
between $if_up and the matching $endif 

.TP 
\fB\*(T<\fBif_updatenr\fR\*(T> \fR\*(T<\fB(updatenr)\fR\*(T> 
If it's the UPDATENR-th time that conky updates,
display everything between $if_updatenr and the matching
$endif. The counter resets when the highest UPDATENR is
reached. Example : "{$if_updatenr 1}foo$endif{$if_updatenr
2}bar$endif{$if_updatenr 4}$endif" shows foo 25% of the
time followed by bar 25% of the time followed by nothing
the other half of the time. 

.TP 
\fB\*(T<\fBif_xmms2_connected\fR\*(T> \fR
Display everything between $if_xmms2_connected
and the matching $endif if xmms2 is running. 

.TP 
\fB\*(T<\fBimage\fR\*(T> \fR\*(T<\fB<path to image> (\-p x,y) (\-s WxH) (\-n) (\-f interval)\fR\*(T> 
Renders an image from the path specified using
Imlib2. Takes 4 optional arguments: a position, a size, a
no-cache switch, and a cache flush interval. Changing the
x,y position will move the position of the image, and
changing the WxH will scale the image. If you specify the
no-cache flag (-n), the image will not be cached.
Alternately, you can specify the -f int switch to specify a
cache flust interval for a particular image. Example:
${image /home/brenden/cheeseburger.jpg -p 20,20 -s 200x200}
will render 'cheeseburger.jpg' at (20,20) scaled to 200x200
pixels. Conky does not make any attempt to adjust the
position (or any other formatting) of images, they are just
rendered as per the arguments passed. The only reason
$image is part of the TEXT section, is to allow for runtime
modifications, through $execp $lua_parse, or some other
method. 

.TP 
\fB\*(T<\fBimap_messages\fR\*(T> \fR\*(T<\fB(args)\fR\*(T> 
Displays the number of messages in your global
IMAP inbox by default. You can define individual IMAP
inboxes separately by passing arguments to this object.
Arguments are: "host user pass [-i interval (in seconds)]
[-f 'folder'] [-p port] [-e 'command'] [-r retries]". Default
port is 143, default folder is 'INBOX', default interval is
5 minutes, and default number of retries before giving up
is 5. If the password is supplied as '*', you will be
prompted to enter the password when Conky starts. 

.TP 
\fB\*(T<\fBimap_unseen\fR\*(T> \fR\*(T<\fB(args)\fR\*(T> 
Displays the number of unseen messages in your
global IMAP inbox by default. You can define individual
IMAP inboxes separately by passing arguments to this
object. Arguments are: "host user pass [-i interval (in
seconds)] [-f 'folder'] [-p port] [-e 'command'] [-r retries]".
Default port is 143, default folder is 'INBOX', default
interval is 5 minutes, and default number of retries before
giving up is 5. If the password is supplied as '*', you
will be prompted to enter the password when Conky starts. 

.TP 
\fB\*(T<\fBinclude\fR\*(T> \fR\*(T<\fBpath\fR\*(T> 
Loads the configfile at path, places the
configsettings behind the configsettings in the orginal
config and places the vars where the includevar
stood.
.TP 
\fB\*(T<\fBioscheduler\fR\*(T> \fR\*(T<\fBdisk\fR\*(T> 
Prints the current ioscheduler used for the given
disk name (i.e. e.g. "hda" or "sdb") 

.TP 
\fB\*(T<\fBkernel\fR\*(T> \fR
Kernel version 

.TP 
\fB\*(T<\fBlaptop_mode\fR\*(T> \fR
The value of /proc/sys/vm/laptop_mode 

.TP 
\fB\*(T<\fBlines\fR\*(T> \fR\*(T<\fBtextfile\fR\*(T> 
Displays the number of lines in the given file 

.TP 
\fB\*(T<\fBloadavg\fR\*(T> \fR\*(T<\fB(1|2|3)\fR\*(T> 
System load average, 1 is for past 1 minute, 2
for past 5 minutes and 3 for past 15 minutes. Without argument, prints
all three values separated by whitespace.

.TP 
\fB\*(T<\fBloadgraph\fR\*(T> \fR\*(T<\fB(height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Load1 average graph, similar to xload, with
optional colours in hex, minus the #. Uses a logarithmic
scale (to see small numbers) when you use the -l switch.
Takes the switch '-t' to use a temperature gradient, which
makes the gradient values change depending on the amplitude
of a particular graph value (try it and see). 

.TP 
\fB\*(T<\fBlua\fR\*(T> \fR\*(T<\fBfunction_name (function parameters)\fR\*(T> 
Executes a Lua function with given parameters,
then prints the returned string. See also 'lua_load' on how
to load scripts. Conky puts 'conky_' in front of
function_name to prevent accidental calls to the wrong
function unless you put you place 'conky_' in front of it
yourself. 

.TP 
\fB\*(T<\fBlua_bar\fR\*(T> \fR\*(T<\fB(height, width) function_name (function parameters)\fR\*(T> 
Executes a Lua function with given parameters and
draws a bar. Expects result value to be an integer between
0 and 100. See also 'lua_load' on how to load scripts.
Conky puts 'conky_' in front of function_name to prevent
accidental calls to the wrong function unless you put you
place 'conky_' in front of it yourself. 

.TP 
\fB\*(T<\fBlua_gauge\fR\*(T> \fR\*(T<\fB(height, width) function_name (function parameters)\fR\*(T> 
Executes a Lua function with given parameters and
draws a gauge. Expects result value to be an integer
between 0 and 100. See also 'lua_load' on how to load
scripts. Conky puts 'conky_' in front of function_name to
prevent accidental calls to the wrong function unless you
put you place 'conky_' in front of it yourself. 

.TP 
\fB\*(T<\fBlua_graph\fR\*(T> \fR\*(T<\fBfunction_name (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Executes a Lua function with and draws a graph.
Expects result value to be any number, and by default will
scale to show the full range. See also 'lua_load' on how to
load scripts. Takes the switch '-t' to use a temperature
gradient, which makes the gradient values change depending
on the amplitude of a particular graph value (try it and
see). Conky puts 'conky_' in front of function_name to
prevent accidental calls to the wrong function unless you
put you place 'conky_' in front of it yourself. 

.TP 
\fB\*(T<\fBlua_parse\fR\*(T> \fR\*(T<\fBfunction_name (function parameters)\fR\*(T> 
Executes a Lua function with given parameters as
per $lua, then parses and prints the result value as per
the syntax for Conky's TEXT section. See also 'lua_load' on
how to load scripts. Conky puts 'conky_' in front of
function_name to prevent accidental calls to the wrong
function unless you put you place 'conky_' in front of it
yourself. 

.TP 
\fB\*(T<\fBmachine\fR\*(T> \fR
Machine, i686 for example 

.TP 
\fB\*(T<\fBmails\fR\*(T> \fR\*(T<\fB(mailbox)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Mail count in the specified mailbox or your mail
spool if not. Both mbox and maildir type mailboxes are
supported. You can use a program like fetchmail to get
mails from some server using your favourite protocol. See
also new_mails. 

.TP 
\fB\*(T<\fBmboxscan\fR\*(T> \fR\*(T<\fB(\-n number of messages to print) (\-fw from width) (\-sw subject width) mbox\fR\*(T> 
Print a summary of recent messages in an mbox
format mailbox. mbox parameter is the filename of the
mailbox (can be encapsulated using '"', ie. ${mboxscan -n
10 "/home/brenden/some box"} 

.TP 
\fB\*(T<\fBmem\fR\*(T> \fR
Amount of memory in use 

.TP 
\fB\*(T<\fBmembar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Bar that shows amount of memory in use 

.TP 
\fB\*(T<\fBmemeasyfree\fR\*(T> \fR
Amount of free memory including the memory that
is very easily freed (buffers/cache) 

.TP 
\fB\*(T<\fBmemfree\fR\*(T> \fR
Amount of free memory 

.TP 
\fB\*(T<\fBmemgauge\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Gauge that shows amount of memory in use (see
cpugauge) 

.TP 
\fB\*(T<\fBmemgraph\fR\*(T> \fR\*(T<\fB(height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Memory usage graph. Uses a logarithmic scale (to
see small numbers) when you use the -l switch. Takes the
switch '-t' to use a temperature gradient, which makes the
gradient values change depending on the amplitude of a
particular graph value (try it and see). 

.TP 
\fB\*(T<\fBmemmax\fR\*(T> \fR
Total amount of memory 

.TP 
\fB\*(T<\fBmemperc\fR\*(T> \fR
Percentage of memory in use 

.TP 
\fB\*(T<\fBmixer\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Prints the mixer value as reported by the OS.
On Linux, this variable uses the OSS emulation, so you
need the proper kernel module loaded.
Default mixer is "Vol", but you can specify one of the
available OSS controls: "Vol", "Bass", "Trebl", "Synth",
"Pcm", "Spkr", "Line", "Mic", "CD", "Mix", "Pcm2 ", "Rec",
"IGain", "OGain", "Line1", "Line2", "Line3", "Digital1",
"Digital2", "Digital3", "PhoneIn", "PhoneOut", "Video",
"Radio" and "Monitor".

.TP 
\fB\*(T<\fBmixerbar\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays mixer value in a bar as reported by the
OS. See docs for $mixer for details on arguments. 

.TP 
\fB\*(T<\fBmixerl\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Prints the left channel mixer value as reported
by the OS. See docs for $mixer for details on arguments. 

.TP 
\fB\*(T<\fBmixerlbar\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays the left channel mixer value in a bar as
reported by the OS. See docs for $mixer for details on
arguments. 

.TP 
\fB\*(T<\fBmixerr\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Prints the right channel mixer value as reported
by the OS. See docs for $mixer for details on arguments. 

.TP 
\fB\*(T<\fBmixerrbar\fR\*(T> \fR\*(T<\fB(device)\fR\*(T> 
Displays the right channel mixer value in a bar
as reported by the OS. See docs for $mixer for details on
arguments. 

.TP 
\fB\*(T<\fBmoc_album\fR\*(T> \fR
Album of the current MOC song 

.TP 
\fB\*(T<\fBmoc_artist\fR\*(T> \fR
Artist of the current MOC song 

.TP 
\fB\*(T<\fBmoc_bitrate\fR\*(T> \fR
Bitrate in the current MOC song 

.TP 
\fB\*(T<\fBmoc_curtime\fR\*(T> \fR
Current time of the current MOC song 

.TP 
\fB\*(T<\fBmoc_file\fR\*(T> \fR
File name of the current MOC song 

.TP 
\fB\*(T<\fBmoc_rate\fR\*(T> \fR
Rate of the current MOC song 

.TP 
\fB\*(T<\fBmoc_song\fR\*(T> \fR
The current song name being played in MOC. 

.TP 
\fB\*(T<\fBmoc_state\fR\*(T> \fR
Current state of MOC; playing, stopped etc. 

.TP 
\fB\*(T<\fBmoc_timeleft\fR\*(T> \fR
Time left in the current MOC song 

.TP 
\fB\*(T<\fBmoc_title\fR\*(T> \fR
Title of the current MOC song 

.TP 
\fB\*(T<\fBmoc_totaltime\fR\*(T> \fR
Total length of the current MOC song 

.TP 
\fB\*(T<\fBmonitor\fR\*(T> \fR
Number of the monitor on which conky is running
or the message "Not running in X" if this is the case. 

.TP 
\fB\*(T<\fBmonitor_number\fR\*(T> \fR
Number of monitors or the message "Not running in
X" if this is the case. 

.TP 
\fB\*(T<\fBmpd_album\fR\*(T> \fR
Album in current MPD song 

.TP 
\fB\*(T<\fBmpd_artist\fR\*(T> \fR
Artist in current MPD song must be enabled at
compile 

.TP 
\fB\*(T<\fBmpd_bar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Bar of mpd's progress 

.TP 
\fB\*(T<\fBmpd_bitrate\fR\*(T> \fR
Bitrate of current song 

.TP 
\fB\*(T<\fBmpd_date\fR\*(T> \fR
Date of current song

.TP 
\fB\*(T<\fBmpd_elapsed\fR\*(T> \fR
Song's elapsed time 

.TP 
\fB\*(T<\fBmpd_file\fR\*(T> \fR
Prints the file name of the current MPD song 

.TP 
\fB\*(T<\fBmpd_length\fR\*(T> \fR
Song's length 

.TP 
\fB\*(T<\fBmpd_name\fR\*(T> \fR
Prints the MPD name field 

.TP 
\fB\*(T<\fBmpd_percent\fR\*(T> \fR
Percent of song's progress 

.TP 
\fB\*(T<\fBmpd_random\fR\*(T> \fR
Random status (On/Off) 

.TP 
\fB\*(T<\fBmpd_repeat\fR\*(T> \fR
Repeat status (On/Off) 

.TP 
\fB\*(T<\fBmpd_smart\fR\*(T> \fR\*(T<\fB(max length)\fR\*(T> 
Prints the song name in either the form "artist -
title" or file name, depending on whats available 

.TP 
\fB\*(T<\fBmpd_status\fR\*(T> \fR
Playing, stopped, et cetera. 

.TP 
\fB\*(T<\fBmpd_title\fR\*(T> \fR\*(T<\fB(max length)\fR\*(T> 
Title of current MPD song 

.TP 
\fB\*(T<\fBmpd_track\fR\*(T> \fR
Prints the MPD track field 

.TP 
\fB\*(T<\fBmpd_vol\fR\*(T> \fR
MPD's volume 

.TP 
\fB\*(T<\fBnameserver\fR\*(T> \fR\*(T<\fB(index)\fR\*(T> 
Print a nameserver from /etc/resolv.conf. Index
starts at and defaults to 0. 

.TP 
\fB\*(T<\fBnew_mails\fR\*(T> \fR\*(T<\fB(mailbox)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Unread mail count in the specified mailbox or
mail spool if not. Both mbox and maildir type mailboxes are
supported. 

.TP 
\fB\*(T<\fBnodename\fR\*(T> \fR
Hostname 

.TP 
\fB\*(T<\fBnodename_short\fR\*(T> \fR
Short hostname (same as 'hostname -s' shell command).

.TP 
\fB\*(T<\fBnvidia\fR\*(T> \fR\*(T<\fBthreshold\fR\*(T> \*(T<\fBtemp\fR\*(T> \*(T<\fBambient\fR\*(T> \*(T<\fBgpufreq\fR\*(T> \*(T<\fBmemfreq\fR\*(T> \*(T<\fBimagequality\fR\*(T> 
Nvidia graficcard support for the XNVCtrl
library. Each option can be shortened to the least
significant part. Temperatures are printed as float, all
other values as integer. 

\fBthreshold\fR
\*(T<\fBThe thresholdtemperature at
which the gpu slows down\fR\*(T>
.br
\fBtemp\fR
\*(T<\fBGives the gpu current
temperature\fR\*(T>
.br
\fBambient\fR
\*(T<\fBGives current air temperature near GPU
case\fR\*(T>
.br
\fBgpufreq\fR
\*(T<\fBGives the current gpu frequency\fR\*(T>
.br
\fBmemfreq\fR
\*(T<\fBGives the current mem frequency\fR\*(T>
.br
\fBimagequality\fR
\*(T<\fBWhich imagequality should be chosen by
OpenGL applications\fR\*(T>

.TP 
\fB\*(T<\fBoffset\fR\*(T> \fR\*(T<\fB(pixels)\fR\*(T> 
Move text over by N pixels. See also $voffset. 

.TP 
\fB\*(T<\fBoutlinecolor\fR\*(T> \fR\*(T<\fB(color)\fR\*(T> 
Change outline color 

.TP 
\fB\*(T<\fBpb_battery\fR\*(T> \fR\*(T<\fBitem\fR\*(T> 
If running on Apple powerbook/ibook, display
information on battery status. The item parameter
specifies, what information to display. Exactly one item
must be specified. Valid items are: 

\fBstatus\fR
\*(T<\fBDisplay if battery is fully charged,
charging, discharging or absent (running on
AC)\fR\*(T>
.br
\fBpercent\fR
\*(T<\fBDisplay charge of battery in percent, if
charging or discharging. Nothing will be displayed,
if battery is fully charged or absent.\fR\*(T>
.br
\fBtime\fR
\*(T<\fBDisplay the time remaining until the
battery will be fully charged or discharged at
current rate. Nothing is displayed, if battery is
absent or if it's present but fully charged and not
discharging.\fR\*(T>

.TP 
\fB\*(T<\fBpid_chroot\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Directory used as rootdirectory by the process
(this will be "/" unless the process did a chroot syscall)

.TP 
\fB\*(T<\fBpid_cmdline\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Command line this process was invoked with

.TP 
\fB\*(T<\fBpid_cwd\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Current working directory of the process

.TP 
\fB\*(T<\fBpid_environ\fR\*(T> \fR\*(T<\fBpid varname\fR\*(T> 
Contents of a environment-var of the process

.TP 
\fB\*(T<\fBpid_environ_list\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
List of environment-vars that the process can see

.TP 
\fB\*(T<\fBpid_exe\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Path to executed command that started the process

.TP 
\fB\*(T<\fBpid_nice\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The nice value of the process

.TP 
\fB\*(T<\fBpid_openfiles\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
List of files that the process has open

.TP 
\fB\*(T<\fBpid_parent\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The pid of the parent of the process

.TP 
\fB\*(T<\fBpid_priority\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The priority of the process (see 'priority' in "man 5 proc")

.TP 
\fB\*(T<\fBpid_read\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Total number of bytes read by the process

.TP 
\fB\*(T<\fBpid_state\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
State of the process

.TP 
\fB\*(T<\fBpid_state_short\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
One of the chars in "RSDZTW" representing the state
of the process where R is running, S is sleeping in an
interruptible wait, D is waiting in uninterruptible disk sleep,
Z is zombie, T is traced or stopped (on a signal), and W is paging

.TP 
\fB\*(T<\fBpid_stderr\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Filedescriptor binded to the STDERR of the process

.TP 
\fB\*(T<\fBpid_stdin\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Filedescriptor binded to the STDIN of the process

.TP 
\fB\*(T<\fBpid_stdout\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Filedescriptor binded to the STDOUT of the process

.TP 
\fB\*(T<\fBpid_threads\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Number of threads in process containing this thread

.TP 
\fB\*(T<\fBpid_thread_list\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
List with pid's from threads from this process

.TP 
\fB\*(T<\fBpid_time_kernelmode\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Amount of time that the process has been scheduled in kernel mode in seconds

.TP 
\fB\*(T<\fBpid_time_usermode\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Amount of time that the process has been scheduled in user mode in seconds

.TP 
\fB\*(T<\fBpid_time\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Sum of $pid_time_kernelmode and $pid_time_usermode

.TP 
\fB\*(T<\fBpid_uid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The real uid of the process

.TP 
\fB\*(T<\fBpid_euid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The effective uid of the process

.TP 
\fB\*(T<\fBpid_suid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The saved set uid of the process

.TP 
\fB\*(T<\fBpid_fsuid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The file system uid of the process

.TP 
\fB\*(T<\fBpid_gid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The real gid of the process

.TP 
\fB\*(T<\fBpid_egid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The effective gid of the process

.TP 
\fB\*(T<\fBpid_sgid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The saved set gid of the process

.TP 
\fB\*(T<\fBpid_fsgid\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
The file system gid of the process

.TP 
\fB\*(T<\fBpid_vmpeak\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Peak virtual memory size of the process

.TP 
\fB\*(T<\fBpid_vmsize\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Virtual memory size of the process

.TP 
\fB\*(T<\fBpid_vmlck\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Locked memory size of the process

.TP 
\fB\*(T<\fBpid_vmhwm\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Peak resident set size ("high water mark") of the process

.TP 
\fB\*(T<\fBpid_vmrss\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Resident set size of the process

.TP 
\fB\*(T<\fBpid_vmdata\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Data segment size of the process

.TP 
\fB\*(T<\fBpid_vmstk\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Stack segment size of the process

.TP 
\fB\*(T<\fBpid_vmexe\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Text segment size of the process

.TP 
\fB\*(T<\fBpid_vmlib\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Shared library code size of the process

.TP 
\fB\*(T<\fBpid_vmpte\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Page table entries size of the process

.TP 
\fB\*(T<\fBpid_write\fR\*(T> \fR\*(T<\fBpid\fR\*(T> 
Total number of bytes written by the process

.TP 
\fB\*(T<\fBplatform\fR\*(T> \fR\*(T<\fB(dev) type n (factor offset)\fR\*(T> 
Platform sensor from sysfs (Linux 2.6). Parameter
dev may be omitted if you have only one platform device.
Platform type is either 'in' or 'vol' meaning voltage;
\&'fan' meaning fan; 'temp' meaning temperature. Parameter n
is number of the sensor. See /sys/bus/platform/devices/ on
your local computer. The optional arguments 'factor' and
\&'offset' allow precalculation of the raw input, which is
being modified as follows: 'input = input * factor +
offset'. Note that they have to be given as decimal values
(i.e. contain at least one decimal place). 

.TP 
\fB\*(T<\fBpop3_unseen\fR\*(T> \fR\*(T<\fB(args)\fR\*(T> 
Displays the number of unseen messages in your
global POP3 inbox by default. You can define individual
POP3 inboxes separately by passing arguments to this
object. Arguments are: "host user pass [-i interval (in
seconds)] [-p port] [-e 'command'] [-r retries]". Default
port is 110, default interval is 5 minutes, and default
number of retries before giving up is 5. If the password is
supplied as '*', you will be prompted to enter the password
when Conky starts. 

.TP 
\fB\*(T<\fBpop3_used\fR\*(T> \fR\*(T<\fB(args)\fR\*(T> 
Displays the amount of space (in MiB, 2^20) used
in your global POP3 inbox by default. You can define
individual POP3 inboxes separately by passing arguments to
this object. Arguments are: "host user pass [-i interval
(in seconds)] [-p port] [-e 'command'] [-r retries]". Default
port is 110, default interval is 5 minutes, and default
number of retries before giving up is 5. If the password is
supplied as '*', you will be prompted to enter the password
when Conky starts. 

.TP 
\fB\*(T<\fBpre_exec\fR\*(T> \fR\*(T<\fBshell command\fR\*(T> 
Executes a shell command one time before conky
displays anything and puts output as text. 

.TP 
\fB\*(T<\fBprocesses\fR\*(T> \fR
Total processes (sleeping and running) 

.TP 
\fB\*(T<\fBread_tcp\fR\*(T> \fR\*(T<\fB(host) port\fR\*(T> 
Connects to a tcp port on a host (default is
localhost), reads every char available at the moment and
shows them. 

.TP 
\fB\*(T<\fBreplied_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as replied in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBrss\fR\*(T> \fR\*(T<\fBuri interval_in_minutes action (num_par (spaces_in_front))\fR\*(T> 
Download and parse RSS feeds. The interval may be
a floating point value greater than 0, otherwise
defaults to 15 minutes. Action may be one of the
following: feed_title, item_title (with num par),
item_desc (with num par) and item_titles (when using
this action and spaces_in_front is given conky places
that many spaces in front of each item). This object is
threaded, and once a thread is created it can't be
explicitly destroyed. One thread will run for each URI
specified. You can use any protocol that Curl
supports.
.TP 
\fB\*(T<\fBrunning_processes\fR\*(T> \fR
Running processes (not sleeping), requires Linux
2.6 

.TP 
\fB\*(T<\fBrunning_threads\fR\*(T> \fR
Number of running (runnable) threads. Linux only.

.TP 
\fB\*(T<\fBscroll\fR\*(T> \fR\*(T<\fBlength (step) text\fR\*(T> 
Scroll 'text' by 'step' characters showing
\&'length' number of characters at the same time. The text
may also contain variables. 'step' is optional and defaults
to 1 if not set. If a var creates output on multiple lines
then the lines are placed behind each other separated with
a '|'-sign. If you change the textcolor inside $scroll it
will automatically have it's old value back at the end of
$scroll. The end and the start of text will be separated by
\&'length' number of spaces. 

.TP 
\fB\*(T<\fBseen_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as seen in the specified
mailbox or mail spool if not. Only maildir type mailboxes
are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBshadecolor\fR\*(T> \fR\*(T<\fB(color)\fR\*(T> 
Change shading color 

.TP 
\fB\*(T<\fBsmapi\fR\*(T> \fR\*(T<\fB(ARGS)\fR\*(T> 
when using smapi, display contents of the
/sys/devices/platform/smapi directory. ARGS are either
\&'(FILENAME)' or 'bat (INDEX) (FILENAME)' to display the
corresponding files' content. This is a very raw method of
accessing the smapi values. When available, better use one
of the smapi_* variables instead. 

.TP 
\fB\*(T<\fBsmapi_bat_bar\fR\*(T> \fR\*(T<\fB(INDEX),(height),(width)\fR\*(T> 
when using smapi, display the remaining capacity
of the battery with index INDEX as a bar. 

.TP 
\fB\*(T<\fBsmapi_bat_perc\fR\*(T> \fR\*(T<\fB(INDEX)\fR\*(T> 
when using smapi, display the remaining capacity
in percent of the battery with index INDEX. This is a
separate variable because it supports the 'use_spacer'
configuration option. 

.TP 
\fB\*(T<\fBsmapi_bat_power\fR\*(T> \fR\*(T<\fBINDEX\fR\*(T> 
when using smapi, display the current power of
the battery with index INDEX in watt. This is a separate
variable because the original read out value is being
converted from mW. The sign of the output reflects charging
(positive) or discharging (negative) state. 

.TP 
\fB\*(T<\fBsmapi_bat_temp\fR\*(T> \fR\*(T<\fBINDEX\fR\*(T> 
when using smapi, display the current temperature
of the battery with index INDEX in degree Celsius. This is
a separate variable because the original read out value is
being converted from milli degree Celsius. 

.TP 
\fB\*(T<\fBsony_fanspeed\fR\*(T> \fR
Displays the Sony VAIO fanspeed information if
sony-laptop kernel support is enabled. Linux only. 

.TP 
\fB\*(T<\fBstippled_hr\fR\*(T> \fR\*(T<\fB(space)\fR\*(T> 
Stippled (dashed) horizontal line 

.TP 
\fB\*(T<\fBswap\fR\*(T> \fR
Amount of swap in use 

.TP 
\fB\*(T<\fBswapbar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Bar that shows amount of swap in use 

.TP 
\fB\*(T<\fBswapfree\fR\*(T> \fR
Amount of free swap 

.TP 
\fB\*(T<\fBswapmax\fR\*(T> \fR
Total amount of swap 

.TP 
\fB\*(T<\fBswapperc\fR\*(T> \fR
Percentage of swap in use 

.TP 
\fB\*(T<\fBsysname\fR\*(T> \fR
System name, Linux for example 

.TP 
\fB\*(T<\fBtab\fR\*(T> \fR\*(T<\fB(width, (start))\fR\*(T> 
Puts a tab of the specified width, starting from
column 'start'. The unit is pixels for both arguments. 

.TP 
\fB\*(T<\fBtail\fR\*(T> \fR\*(T<\fBlogfile lines (next_check)\fR\*(T> 
Displays last N lines of supplied text file. The
file is checked every 'next_check' update. If next_check is
not supplied, Conky defaults to 2. Max of 30 lines can be
displayed, or until the text buffer is filled. 

.TP 
\fB\*(T<\fBtcp_portmon\fR\*(T> \fR\*(T<\fBport_begin port_end item (index)\fR\*(T> 
TCP port (both IPv6 and IPv4) monitor for
specified local ports. Port numbers must be in
the range 1 to 65535. Valid items are:

\fBcount\fR
\*(T<\fBTotal number of connections in the
range\fR\*(T>
.br
\fBrip\fR
\*(T<\fBRemote ip address\fR\*(T>
.br
\fBrhost\fR
\*(T<\fBRemote host name\fR\*(T>
.br
\fBrport\fR
\*(T<\fBRemote port number\fR\*(T>
.br
\fBrservice\fR
\*(T<\fBRemote service name from
/etc/services\fR\*(T>
.br
\fBlip\fR
\*(T<\fBLocal ip address\fR\*(T>
.br
\fBlhost\fR
\*(T<\fBLocal host name\fR\*(T>
.br
\fBlport\fR
\*(T<\fBLocal port number\fR\*(T>
.br
\fBlservice\fR
\*(T<\fBLocal service name from
/etc/services\fR\*(T>

The connection index provides you with access to
each connection in the port monitor. The monitor will
return information for index values from 0 to n-1
connections. Values higher than n-1 are simply ignored.
For the "count" item, the connection index must be
omitted. It is required for all other items.

Examples:

\fB${tcp_portmon 6881 6999
count}\fR
\*(T<\fBDisplays the number of connections in
the bittorrent port range\fR\*(T>
.br
\fB${tcp_portmon 22 22 rip 0}\fR
\*(T<\fBDisplays the remote host ip of the
first sshd connection\fR\*(T>
.br
\fB${tcp_portmon 22 22 rip 9}\fR
\*(T<\fBDisplays the remote host ip of the
tenth sshd connection\fR\*(T>
.br
\fB${tcp_portmon 1 1024 rhost
0}\fR
\*(T<\fBDisplays the remote host name of the
first connection on a privileged port\fR\*(T>
.br
\fB${tcp_portmon 1 1024 rport
4}\fR
\*(T<\fBDisplays the remote host port of the
fifth connection on a privileged port\fR\*(T>
.br
\fB${tcp_portmon 1 65535 lservice
14}\fR
\*(T<\fBDisplays the local service name of the
fifteenth connection in the range of all
ports\fR\*(T>

Note that port monitor variables which share the
same port range actually refer to the same monitor, so
many references to a single port range for different
items and different indexes all use the same monitor
internally. In other words, the program avoids creating
redundant monitors.
.TP 
\fB\*(T<\fBtemplateN\fR\*(T> \fR\*(T<\fB(arg1)\fR\*(T> \*(T<\fB(arg2)\fR\*(T> \*(T<\fB(arg3 ...)\fR\*(T> 
Evaluate the content of the templateN
configuration variable (where N is a value between 0
and 9, inclusively), applying substitutions as
described in the documentation of the corresponding
configuration variable. The number of arguments is
optional, but must match the highest referred index in
the template. You can use the same special sequences in
each argument as the ones valid for a template
definition, e.g. to allow an argument to contain a
whitespace. Also simple nesting of templates is
possible this way.

Here are some examples of template
definitions:

template0 $\e1\e2
.br
template1 \e1: ${fs_used \e2} / ${fs_size
\e2}
.br
template2 \e1 \e2

The following list shows sample usage of the
templates defined above, with the equivalent syntax
when not using any template at all:
.TS
l l.
T{
using template
T}	T{
same without template
T}
.T&
_ _
l l
l l
l l.
T{
${template0 node name}
T}	T{
$nodename
T}
T{
${template1 root /}
T}	T{
root: ${fs_free /} / ${fs_size
/}
T}
T{
${template1
${template2\e disk\e root}
/}
T}	T{
disk root:
${fs_free /} / ${fs_size
/}
T}
.TE
.TP 
\fB\*(T<\fBtexeci\fR\*(T> \fR\*(T<\fBinterval command\fR\*(T> 
Runs a command at an interval inside a thread and
displays the output. Same as $execi, except the command is
run inside a thread. Use this if you have a slow script to
keep Conky updating. You should make the interval slightly
longer then the time it takes your script to execute. For
example, if you have a script that take 5 seconds to
execute, you should make the interval at least 6 seconds.
See also $execi. This object will clean up the thread when
it is destroyed, so it can safely be used in a nested
fashion, though it may not produce the desired behaviour if
used this way. 

.TP 
\fB\*(T<\fBthreads\fR\*(T> \fR
Total threads

.TP 
\fB\*(T<\fBtime\fR\*(T> \fR\*(T<\fB(format)\fR\*(T> 
Local time, see man strftime to get more
information about format 

.TP 
\fB\*(T<\fBto_bytes\fR\*(T> \fR\*(T<\fBsize\fR\*(T> 
If 'size' is a number followed by a size-unit
(kilobyte,mb,GiB,...) then it converts the size to bytes
and shows it without unit, otherwise it just shows 'size'. 

.TP 
\fB\*(T<\fBtop\fR\*(T> \fR\*(T<\fBtype num\fR\*(T> 
This takes arguments in the form:top (name)
(number) Basically, processes are ranked from highest to
lowest in terms of cpu usage, which is what (num)
represents. The types are: "name", "pid", "cpu", "mem",
"mem_res", "mem_vsize", "time", "uid", "user", "io_perc", "io_read" and
"io_write". There can be a max of 10 processes listed. 

.TP 
\fB\*(T<\fBtop_io\fR\*(T> \fR\*(T<\fBtype num\fR\*(T> 
Same as top, except sorted by the amount of I/O
the process has done during the update interval 

.TP 
\fB\*(T<\fBtop_mem\fR\*(T> \fR\*(T<\fBtype num\fR\*(T> 
Same as top, except sorted by mem usage instead
of cpu 

.TP 
\fB\*(T<\fBtop_time\fR\*(T> \fR\*(T<\fBtype num\fR\*(T> 
Same as top, except sorted by total CPU time
instead of current CPU usage 

.TP 
\fB\*(T<\fBtotaldown\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Total download, overflows at 4 GB on Linux with
32-bit arch and there doesn't seem to be a way to know how
many times it has already done that before conky has
started. 

.TP 
\fB\*(T<\fBtotalup\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Total upload, this one too, may overflow 

.TP 
\fB\*(T<\fBtrashed_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails marked as trashed in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBtztime\fR\*(T> \fR\*(T<\fB(timezone (format))\fR\*(T> 
Local time for specified timezone, see man
strftime to get more information about format. The timezone
argument is specified in similar fashion as TZ environment
variable. For hints, look in /usr/share/zoneinfo. e.g.
US/Pacific, Europe/Zurich, etc. 

.TP 
\fB\*(T<\fBgid_name\fR\*(T> \fR\*(T<\fBgid\fR\*(T> 
Name of group with this gid

.TP 
\fB\*(T<\fBuid_name\fR\*(T> \fR\*(T<\fBuid\fR\*(T> 
Username of user with this uid

.TP 
\fB\*(T<\fBunflagged_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails not marked as flagged in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBunforwarded_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails not marked as forwarded in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBunreplied_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of mails not marked as replied in the
specified mailbox or mail spool if not. Only maildir type
mailboxes are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBunseen_mails\fR\*(T> \fR\*(T<\fB(maildir)\fR\*(T> \*(T<\fB(interval)\fR\*(T> 
Number of new or unseen mails in the specified
mailbox or mail spool if not. Only maildir type mailboxes
are supported, mbox type will return -1. 

.TP 
\fB\*(T<\fBupdates\fR\*(T> \fR\*(T<\fBNumber of updates\fR\*(T> 
for debugging 

.TP 
\fB\*(T<\fBupspeed\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Upload speed in suitable IEC units 

.TP 
\fB\*(T<\fBupspeedf\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Upload speed in KiB with one decimal 

.TP 
\fB\*(T<\fBupspeedgraph\fR\*(T> \fR\*(T<\fB(netdev) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (\-t) (\-l)\fR\*(T> 
Upload speed graph, colours defined in hex, minus
the #. If scale is non-zero, it becomes the scale for the
graph. Uses a logarithmic scale (to see small numbers) when
you use the -l switch. Takes the switch '-t' to use a
temperature gradient, which makes the gradient values
change depending on the amplitude of a particular graph
value (try it and see). 

.TP 
\fB\*(T<\fBuptime\fR\*(T> \fR
Uptime 

.TP 
\fB\*(T<\fBuptime_short\fR\*(T> \fR
Uptime in a shorter format 

.TP 
\fB\*(T<\fBuser_names\fR\*(T> \fR
Lists the names of the users logged in 

.TP 
\fB\*(T<\fBuser_number\fR\*(T> \fR
Number of users logged in 

.TP 
\fB\*(T<\fBuser_terms\fR\*(T> \fR
Lists the consoles in use 

.TP 
\fB\*(T<\fBuser_times\fR\*(T> \fR
Lists how long users have been logged in for 

.TP 
\fB\*(T<\fBuser_time\fR\*(T> \fR\*(T<\fBconsole\fR\*(T> 
Lists how long the user for the given console has been
logged in for

.TP 
\fB\*(T<\fButime\fR\*(T> \fR\*(T<\fB(format)\fR\*(T> 
Display time in UTC (universal coordinate time). 

.TP 
\fB\*(T<\fBvoffset\fR\*(T> \fR\*(T<\fB(pixels)\fR\*(T> 
Change vertical offset by N pixels. Negative
values will cause text to overlap. See also $offset. 

.TP 
\fB\*(T<\fBvoltage_mv\fR\*(T> \fR\*(T<\fB(n)\fR\*(T> 
Returns CPU #n's voltage in mV. CPUs are counted
from 1. If omitted, the parameter defaults to 1. 

.TP 
\fB\*(T<\fBvoltage_v\fR\*(T> \fR\*(T<\fB(n)\fR\*(T> 
Returns CPU #n's voltage in V. CPUs are counted
from 1. If omitted, the parameter defaults to 1. 

.TP 
\fB\*(T<\fBweather\fR\*(T> \fR\*(T<\fBURI locID data_type (interval_in_minutes)\fR\*(T> 
Download, parse and display METAR data.

For the 'URI', there are two
possibilities:

http://weather.noaa.gov/pub/data/observations/metar/stations/
.br
http://xoap.weather.com/weather/local/

The first one is free to use but the second
requires you to register and obtain your partner ID and
license key. These two must be written, separated by a
space, into a file called .xoaprc which needs to be
placed into your home directory.

\&'locID' must be a valid location identifier for
the required uri. For the NOAA site this must be a
valid ICAO (see for instance
https://pilotweb.nas.faa.gov/qryhtml/icao/). For the
weather.com site this must be a valid location ID (see
for instance
http://aspnetresources.com/tools/locid.aspx).

\&'data_type' must be one of the following:

\fBlast_update\fR
The date and time stamp of the data.
The result depends on the URI used. For the
NOAA site it is date (yyyy/mm/dd) and UTC time.
For the weather.com one it is date
([m]m/[d]d/yy) and Local Time of the
station.
.br
\fBtemperature\fR

Air temperature (you can use the
\&'temperature_unit' config setting to change
units)
.br
\fBcloud_cover\fR

The highest cloud cover status
.br
\fBpressure\fR

Air pressure in millibar
.br
\fBwind_speed\fR

Wind speed in km/h
.br
\fBwind_dir\fR

Wind direction
.br
\fBwind_dir_DEG\fR

Compass wind direction
.br
\fBhumidity\fR

Relative humidity in %
.br
\fBweather\fR

Any relevant weather event (rain, snow,
etc.). This is not used if you are querying the
weather.com site since this data is aggregated
into the cloud_cover one
.br
\fBicon\fR

Weather icon (only for
www.weather.com). Can be used together with the
icon kit provided upon registering to their
service.

\&'delay_in_minutes' (optional, default 30) cannot
be less than 30 minutes.

This object is threaded, and once a thread is
created it can't be explicitly destroyed. One thread
will run for each URI specified.

Note that these variables are still EXPERIMENTAL
and can be subject to many future changes.
.TP 
\fB\*(T<\fBweather_forecast\fR\*(T> \fR\*(T<\fBURI locID day data_type (interval_in_minutes)\fR\*(T> 
Download, parse and display weather forecast data
for a given day (daytime only).

For the 'URI', for the time being only
http://xoap.weather.com/weather/local/ is
supported. See 'weather' above for details of usage

\&'locID', see 'weather' above.

\&'day' is a number from 0 (today) to 4 (3 days
after tomorrow).

\&'data_type' must be one of the following:

\fBday\fR
\*(T<\fBDay of the week\fR\*(T>
.br
\fBdate\fR
\*(T<\fBDate, in the form MMM DD (ie. Jul 14)\fR\*(T>
.br
\fBlow\fR
\*(T<\fBMinimun temperature (you can use the
\&'temperature_unit' config setting to change
units)\fR\*(T>
.br
\fBhi\fR
\*(T<\fBMaximum temperature (you can use the
\&'temperature_unit' config setting to change
units)\fR\*(T>
.br
\fBicon\fR
\*(T<\fBWeather icon. Can be used together with the
icon kit provided upon registering to the weather.com
service\fR\*(T>
.br
\fBforecast\fR
\*(T<\fBWeather forecast (sunny, rainy, etc.)\fR\*(T>
.br
\fBwind_speed\fR
\*(T<\fBWind speed in km/h\fR\*(T>
.br
\fBwind_dir\fR
\*(T<\fBWind direction\fR\*(T>
.br
\fBwind_dir_DEG\fR
\*(T<\fBCompass wind direction\fR\*(T>
.br
\fBhumidity\fR
\*(T<\fBRelative humidity in %\fR\*(T>
.br
\fBprecipitation\fR
\*(T<\fBProbability of having a
precipitation (in %)\fR\*(T>

\&'delay_in_minutes' (optional, default 210) cannot
be lower than 210 min.

This object is threaded, and once a thread is
created it can't be explicitly destroyed. One thread
will run for each URI specified. You can use any
protocol that Curl supports.

Note that these variables are still EXPERIMENTAL
and can be subject to many future changes.
.TP 
\fB\*(T<\fBwireless_ap\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless access point MAC address (Linux only) 

.TP 
\fB\*(T<\fBwireless_bitrate\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless bitrate (ie 11 Mb/s) (Linux only) 

.TP 
\fB\*(T<\fBwireless_essid\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless access point ESSID (Linux only) 

.TP 
\fB\*(T<\fBwireless_link_bar\fR\*(T> \fR\*(T<\fB(height),(width) (net)\fR\*(T> 
Wireless link quality bar (Linux only) 

.TP 
\fB\*(T<\fBwireless_link_qual\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless link quality (Linux only) 

.TP 
\fB\*(T<\fBwireless_link_qual_max\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless link quality maximum value (Linux only) 

.TP 
\fB\*(T<\fBwireless_link_qual_perc\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless link quality in percents (Linux only) 

.TP 
\fB\*(T<\fBwireless_mode\fR\*(T> \fR\*(T<\fB(net)\fR\*(T> 
Wireless mode (Managed/Ad-Hoc/Master) (Linux
only) 

.TP 
\fB\*(T<\fBwords\fR\*(T> \fR\*(T<\fBtextfile\fR\*(T> 
Displays the number of words in the given file 

.TP 
\fB\*(T<\fBxmms2_album\fR\*(T> \fR
Album in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_artist\fR\*(T> \fR
Artist in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_bar\fR\*(T> \fR\*(T<\fB(height),(width)\fR\*(T> 
Bar of XMMS2's progress 

.TP 
\fB\*(T<\fBxmms2_bitrate\fR\*(T> \fR
Bitrate of current song 

.TP 
\fB\*(T<\fBxmms2_comment\fR\*(T> \fR
Comment in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_date\fR\*(T> \fR
Returns song's date. 

.TP 
\fB\*(T<\fBxmms2_duration\fR\*(T> \fR
Duration of current song 

.TP 
\fB\*(T<\fBxmms2_elapsed\fR\*(T> \fR
Song's elapsed time 

.TP 
\fB\*(T<\fBxmms2_genre\fR\*(T> \fR
Genre in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_id\fR\*(T> \fR
XMMS2 id of current song 

.TP 
\fB\*(T<\fBxmms2_percent\fR\*(T> \fR
Percent of song's progress 

.TP 
\fB\*(T<\fBxmms2_playlist\fR\*(T> \fR
Returns the XMMS2 playlist. 

.TP 
\fB\*(T<\fBxmms2_size\fR\*(T> \fR
Size of current song 

.TP 
\fB\*(T<\fBxmms2_smart\fR\*(T> \fR
Prints the song name in either the form "artist -
title" or file name, depending on whats available 

.TP 
\fB\*(T<\fBxmms2_status\fR\*(T> \fR
XMMS2 status (Playing, Paused, Stopped, or
Disconnected) 

.TP 
\fB\*(T<\fBxmms2_timesplayed\fR\*(T> \fR
Number of times a song was played (presumably). 

.TP 
\fB\*(T<\fBxmms2_title\fR\*(T> \fR
Title in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_tracknr\fR\*(T> \fR
Track number in current XMMS2 song 

.TP 
\fB\*(T<\fBxmms2_url\fR\*(T> \fR
Full path to current song 

.SH "LUA API"
Conky features a Lua Programming API, and also ships with Lua
bindings for some useful libraries. Conky defines certain global
functions and variables which can be accessed from Lua code running
in Conky.
.PP
To use Lua Conky, you first need to make sure you have a version of Conky
with Lua support enabled (``conky -v'' will report this). Scripts
must first be loaded using the lua_load configuration option. You
then call functions in Lua via Conky's $lua, $lua_read, and Lua
hooks.
.PP
Be careful when creating threaded objects through the Lua API. You
could wind up with a whole bunch of threads running if a thread is
created with each iteration.
.PP
At this time, the Lua API should not be considered stable and may
change drastically from one release to another as it matures.
.PP
NOTE: In order to accommodate certain features in the cairo
library's API, Conky will export a few additional functions for the
creation of certain structures. These are documented below.
.TP 
\fB\*(T<\fBconky_parse(string)\fR\*(T> \fR\*(T<\fBfunction\fR\*(T> 
This function takes a string that is evaluated as
per Conky's TEXT section, and then returns a string
with the result.
.TP 
\fB\*(T<\fBconky_set_update_interval(number)\fR\*(T> \fR\*(T<\fBfunction\fR\*(T> 
Sets Conky's update interval (in seconds) to
\&'number'.
.TP 
\fB\*(T<\fBconky_window\fR\*(T> \fR\*(T<\fBtable\fR\*(T> 
This table contains some information about
Conky's window. The following table describes the
values contained:

\fBdrawable\fR
\*(T<\fBWindow's drawable (Xlib Drawable),
requires Lua extras enabled at compile
time.\fR\*(T>
.br
\fBvisual\fR
\*(T<\fBWindow's visual (Xlib Visual), requires
Lua extras enabled at compile time.\fR\*(T>
.br
\fBdisplay\fR
\*(T<\fBWindow's display (Xlib Display),
requires Lua extras enabled at compile
time.\fR\*(T>
.br
\fBwidth\fR
\*(T<\fBWindow width (in pixels).\fR\*(T>
.br
\fBheight\fR
\*(T<\fBWindow height (in pixels).\fR\*(T>
.br
\fBborder_inner_margin\fR
\*(T<\fBWindow's inner border margin (in
pixels).\fR\*(T>
.br
\fBborder_outer_margin\fR
\*(T<\fBWindow's outer border margin (in
pixels).\fR\*(T>
.br
\fBborder_width\fR
\*(T<\fBWindow's border width (in
pixels).\fR\*(T>
.br
\fBtext_start_x\fR
\*(T<\fBThe x component of the starting
coordinate of text drawing.\fR\*(T>
.br
\fBtext_start_y\fR
\*(T<\fBThe y component of the starting
coordinate of text drawing.\fR\*(T>
.br
\fBtext_width\fR
\*(T<\fBThe width of the text drawing
region.\fR\*(T>
.br
\fBtext_height\fR
\*(T<\fBThe height of the text drawing
region.\fR\*(T>

NOTE: This table is only defined when X support
is enabled.
.TP 
\fB\*(T<\fBconky_info\fR\*(T> \fR\*(T<\fBtable\fR\*(T> 
This table contains some information about
Conky's internal data. The following table describes
the values contained:

\fBupdate_interval\fR
\*(T<\fBConky's update interval (in
seconds).\fR\*(T>
.br
\fBuptime\fR
\*(T<\fBSystem uptime, in seconds.\fR\*(T>
.TP 
\fB\*(T<\fBconky_build_info\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
A string containing the build info for this
particular instance of Conky, including the version,
build date, and architecture.
.TP 
\fB\*(T<\fBconky_build_date\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
A string containing the build date for this
particular instance of Conky.
.TP 
\fB\*(T<\fBconky_build_arch\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
A string containing the build architecture for
this particular instance of Conky.
.TP 
\fB\*(T<\fBconky_version\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
A string containing the version of the current
instance of Conky.
.TP 
\fB\*(T<\fBconky_config\fR\*(T> \fR\*(T<\fBstring\fR\*(T> 
A string containing the path of the current Conky
configuration file.
.TP 
\fB\*(T<\fBcairo_text_extents_t:create()\fR\*(T> \fR\*(T<\fBfunction\fR\*(T> 
Call this function to return a new cairo_text_extents_t structure. A creation function for this structure is not provided by the cairo API. After calling this, you should use tolua.takeownership() on the return value to ensure ownership is passed properly.
.TP 
\fB\*(T<\fBcairo_font_extents_t:create()\fR\*(T> \fR\*(T<\fBfunction\fR\*(T> 
Call this function to return a new cairo_font_extents_t structure. A creation function for this structure is not provided by the cairo API. After calling this, you should use tolua.takeownership() on the return value to ensure ownership is passed properly.
.TP 
\fB\*(T<\fBcairo_matrix_t:create()\fR\*(T> \fR\*(T<\fBfunction\fR\*(T> 
Call this function to return a new cairo_matrix_t structure. A creation function for this structure is not provided by the cairo API. After calling this, you should use tolua.takeownership() on the return value to ensure ownership is passed properly.
.SH EXAMPLES
.TP 
\*(T<conky\*(T> \*(T<\fB\-t '${time %D %H:%M}' \-o \-u 30\fR\*(T> 
Start Conky in its own window with date
and clock as text and 30 sec update
interval.
.TP 
\*(T<conky\*(T> \*(T<\fB\-a top_left \-x 5 \-y 500 \-d\fR\*(T> 
Start Conky to background at coordinates
(5, 500).
.TP 
\*(T<conky\*(T> \*(T<\fB\-C > ~/.conkyrc\fR\*(T> 
Do not start Conky, but have it output
the builtin default config file to ~/.conkyrc for
later customising.
.SH FILES
.TP 
\*(T<\fI${sysconfdir}/conky/conky.conf\fR\*(T> 
Default system-wide configuration file.
The value of ${sysconfdir} depends on the
compile-time options (most likely /etc).
.TP 
\*(T<\fI~/.conkyrc\fR\*(T> 
Default personal configuration
file.
.SH BUGS
Drawing to root or some other desktop window directly
doesn't work with all window managers. Especially doesn't
work well with Gnome and it has been reported that it
doesn't work with KDE either. Nautilus can be disabled from
drawing to desktop with program gconf-editor. Uncheck
show_desktop in /apps/nautilus/preferences/. There is -w
switch in Conky to set some specific window id. You might
find xwininfo -tree useful to find the window to draw to.
You can also use -o argument which makes Conky to create
its own window. If you do try running Conky in its own
window, be sure to read up on the own_window_type settings
and experiment.
.SH "SEE ALSO"
\(lahttp://conky.sourceforge.net/\(ra
.PP
\(lahttp://www.sourceforge.net/projects/conky\(ra
.PP
\(lahttp://wiki.conky.be\(ra
.PP
#conky on irc.freenode.net
.SH COPYING
Copyright (c) 2005-2010 Brenden Matthews, Philip
Kovacs, et. al. Any original torsmo code is licensed under
the BSD license (see LICENSE.BSD for a copy). All code
written since the fork of torsmo is licensed under the GPL
(see LICENSE.GPL for a copy), except where noted
differently (such as in portmon code, timed thread code,
and audacious code which are LGPL, and prss which is an
MIT-style license).
.SH AUTHORS
The Conky dev team (see AUTHORS for a full list of
contributors).
