.\" -*- coding: UTF-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH uptime 1 "3 August 2014" "2014 年 7 月" "GNU coreutils 8.22"
.SH NAME
uptime \- 告诉您系统已运行了多久
.SH SYNOPSIS
'nh
.fi
.ad l
\fBuptime\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[\fI选项\fR]… [\fIFILE\fR]
'in \n(.iu-\nxu
.ad b
'hy
.SH 描述
输出当前时间，系统已运行的时间，系统上的用户数目，以及过去 1、5 和 15 分钟里运行队列中的平均任务数目。处于不间断睡眠状态的进程也会增加平均负载。若未指定文件则使用 \*(T<\fI/var/run/utmp\fR\*(T>。 通常是使用 \*(T<\fI/var/log/wtmp\fR\*(T> 作为 FILE。
.TP 
\*(T<\fB\-\-help\fR\*(T>
显示此帮助并退出
.TP 
\*(T<\fB\-\-version\fR\*(T>
输出版本信息并退出

GNU coreutils 在线帮助：<〈http://www.gnu.org/software/coreutils/>〉 汇报 uptime 翻译故障 <〈http://translationproject.org/team/>〉
.SH 作者
由约瑟夫 · Arceneaux、大卫 · 麦肯齐和 Kaveh Ghazi 编撰
.SH 版权
版权所有 © 2013 自由软件基金会。许可证 GPLv3+：GNU 通用公共许可证 第三版及后续版本 <〈http://gnu.org/licenses/gpl.html>〉。这是一个自由软件：您可以自由修订并分发它。在法律允许范围内不作任何保证。
.SH 继续阅读
\fBuptime\fR 的完整文档以一本 Texinfo 手册的形式维护。若您的计算机上妥善安装了 \fIinfo\fR 和 \fBuptime\fR 程序，这个命令
.PP
\fIinfo coreutils "uptime invocation"\fR
.PP
应可让您调阅完整手册。
